### ISSUE TITLE
In case of POLLERR, no callback is served by the library

### ISSUE THREAD

**Issue by amandeepgautam** [sahlberg/libsmb2#100]
Hi,
   It is more of a question rather than an issue as I am not sure what the behaviour correct behaviour should be.

Problem:
When I get a POLLERR, the client get stuck as the callback is never served.

Analysis:
In the function _smb2_service_ at line: https://github.com/sahlberg/libsmb2/blob/master/lib/socket.c#L557, if we get POLLERR the callback is not served and -1 is returned.
However, at other places in the same function, a callback is served when -1 is the return value. Ex: https://github.com/sahlberg/libsmb2/blob/master/lib/socket.c#L594

Questions I have are below:
-- How is the caller supposed to know when the callback was served and when was it not served?
-- What is the problem is serving the callback always? Specifically, when it is a POLLERR.

Also, please let me know if there is a mailing list where such questions can be asked.

**Comment by amandeepgautam** [comment]
Sent a pull request here: https://github.com/sahlberg/libsmb2/pull/169

**Comment by sahlberg** [comment]
Merged.
