### ISSUE TITLE
Regression: not able to connect to password-less Windows 10 shares

### ISSUE THREAD

**Issue by tguillem** [sahlberg/libsmb2#103]
Hello,

There is a regression from 938cc11fabfb7c31e88ffcd2d04fce859664a9e1 "fix correct length for error PDUs"

With this commit, the smb2 fd won't be notified from poll() after a smb2_connect_share_async() call.

Reverting this commit fixes my issue.

How to reproduce:
 - Setup a Windows 10 share
 - Type the Window key and "Manage advanced sharing settings"
 - In the "All networks category", tick "Turn off password protected sharing" at the bottom.

Maybe, it happen with more SMB configurations.

**Comment by sahlberg** [comment]
Can you send me a network trace of this?
I want to check something and possibly solve it a different way.
(I.e. instead of as the spec says that there MUST be at least one byte)

Otherwise I will just revert it.

**Comment by tguillem** [comment]
Here is the pcapng dump (zipped to make github happy).

[smb2-fail.zip](https://github.com/sahlberg/libsmb2/files/3739016/smb2-fail.zip)

**Comment by sahlberg** [comment]
Thankyou!

It confirms what I suspected.   The server actually violates the SMB2
spec which says :

"If the ByteCount field is zero then the server MUST supply an
ErrorData field that is one byte in
length,"

but in packet #10 we have no extra byte there, causing libsmb2 to
hang, waiting for that extra byte that will never arrive.


The correct fix would be to check if there is an extra byte there and
not assume there must be one byte.
I.e. checking if there is any padding following the fixed 8 bytes of
the error reply and ONLY read this extra byte iff padding is >= 1
byte.

But I will probably just revert that patch for now and go back to the
original behavior where in this case any additional bytes would just
be considered padding.
In this situation the content of the extra byte is undefined and must
be ignored anyway so,   the easiest path forward wins...

**Comment by sahlberg** [comment]
I reverted the patch.

**Comment by tguillem** [comment]
If even MS is not respecting its spec...

Thanks for quick fix anyway !

By the way, did you see my PR https://github.com/sahlberg/libsmb2/pull/102 ?

**Comment by sahlberg** [comment]
On Thu, Oct 17, 2019 at 10:50 PM Thomas Guillem <notifications@github.com>
wrote:

> If even MS is not respecting its spec...
>
> Thanks for quick fix anyway !
>
> By the way, did you see my PR #102
> <https://github.com/sahlberg/libsmb2/pull/102> ?
>

Missed it.  But I have merged it now. thanks!
