### ISSUE TITLE
Feature request: automatically fall back on internal ntlmssp implementation when using kerberos on windows

### ISSUE THREAD

**Issue by timmeh87** [sahlberg/libsmb2#114]
Currently, the official advice is to build the "gss-ntlmssp" plugin in order to use ntlmssp when also using the kerberos library.

I wanted to make a windows build that supported both kerberos and ntlmssp auth, so I tried to accomplish this. However the gss-ntlmssp library does not support windows (it has several linux dependencies and cannot be easily ported).

I thought it was a little frustrating that I can build the library to support either kerberos or ntlmssp, but not both, so I had a simple idea:

- in the headers, everywhere the was an #ifdef/#ifndef HAVE_LIBKRB5, I removed it so that all related headers are included at once.
- in the source code, everywhere the was was an `#ifdef/#ifndef HAVE_LIBKRB5` i changed it to an actual if statement that checks `if (smb2->sec == SMB2_SEC_NTLMSSP){` and then uses the included ntlmspp implementation in the case that that is true.

it seems to work for me, but i am not comfortable making pull requests to this project, and also my implementation does not correctly handle the case where the user *actually* doesn't have the krb5 library, then my version of the code will not compile. A real implementation would require another switch like "HAVE_GSS_NTLMSPP" inside of "HAVE_LIBKRB5" and have that tied into the whole cmake system

**Comment by sahlberg** [comment]
On Sat, Oct 19, 2019 at 6:39 AM timmeh87 <notifications@github.com> wrote:

> Currently, the official advice is to build the "gss-ntlmssp" plugin in
> order to use ntlmssp when also using the kerberos library.
>
> I wanted to make a windows build that supported both kerberos and ntlmssp
> auth, so I tried to accomplish this. However the gss-ntlmssp library does
> not support windows (it has several linux dependencies and cannot be easily
> ported).
>

Yeah, I want to get rid of gss-api and that mech for various reasons and
reimplement it insode the library but that is not short term solution.

> I thought it was a little frustrating that I can build the library to
> support either kerberos or ntlmssp, but not both, so I had a simple idea:
>

But you can!
If you specify "sec=ntlmssp" as part of the URL or if you programatically
call smb2_set_authentication(smb2, SMB2_SEC_NTLMSSP)
then the library should use the builtin NTLMSSP implementation even if you
link with gssapi.

Does this not work for you? (using the latest version from my repo)

**Comment by timmeh87** [comment]
Oh jeez I guess someone added it since the 3.0.0 release. I mean, I just checked, that seems to be exactly what happened. Sorry to be a bother

**Comment by sahlberg** [comment]
No worries mate.
Thanks for using libsmb2.

If you want to, I am always curious about the use-cases for my libraries to better understand the consumers of said library.
I had one user that used it to build a SMB2 offload HW card for his TRS-80!!!!
Completely madly awesome.

If you want to, and can,  tell me about your project and use case, please mail me at ronniesahlberg@gmail.com  I love to hear about what projects people use libsmb2 for.
