### ISSUE TITLE
Problems using examples

### ISSUE THREAD

**Issue by lrusak** [sahlberg/libsmb2#12]
I'm trying to use the examples to make sure the code works properly but I can't seem to connect to my share
```
$ ./smb2-ls-sync smb://192.168.1.106/concerts/
smb2_connect_share failed. gss_init_sec_context: (Unspecified GSS failure.  Minor code may provide more information,  SPNEGO cannot find mechanisms to negotiate)
```
I'm just trying to use anonymous guest but I'm not sure about the url
I've tried a bunch of various urls with no success
```
smb://Guest:@192.168.1.106/concerts/
smb://guest:@192.168.1.106/concerts/
smb://192.168.1.106/concerts/
```

Any ideas about what I'm doing wrong would be great

**Comment by sahlberg** [comment]
"SPNEGO cannot find mechanisms to negotiate)"
I think this means you did not set up the mech correctly.
See the file '/etc/gss/mech.d/ntlmssp.conf' below.




For the kerberos library, you need to set up a basic /etc/krb5.conf file,
even if we are not going to use kerberos but rather NTLM.
The library just needs a krb5.conf file.


This is the one I use, it is basically just a template:
===
$ cat /etc/krb5.conf
# To opt out of the system crypto-policies configuration of krb5, remove the
# symlink at /etc/krb5.conf.d/crypto-policies which will not be recreated.
includedir /etc/krb5.conf.d/

[logging]
 default = FILE:/var/log/krb5libs.log
 kdc = FILE:/var/log/krb5kdc.log
 admin_server = FILE:/var/log/kadmind.log

[libdefaults]
 dns_lookup_realm = false
 ticket_lifetime = 24h
 renew_lifetime = 7d
 forwardable = true
 rdns = false
# default_realm = EXAMPLE.COM
 default_ccache_name = KEYRING:persistent:%{uid}

[realms]
 EXAMPLE.COM = {
  kdc = kerberos.example.com
  admin_server = kerberos.example.com
 }

domain_realm]
 .example.com = EXAMPLE.COM
 example.com = EXAMPLE.COM
===

Make sure you have comiled and installed the GSS-NTLMSSP plugin.

Make sure you also have configured kerberos to know about this plugin.


On fedora you do it using this file:
===
$ cat /etc/gss/mech.d/ntlmssp.conf
# NTLMSSP mechanism plugin
#
# NOTE: to activate the NTLM SSP mechanism do the following
#     * FOR krb5 < 1.12: copy the content of this file in /etc/gss/mech
#     * FOR krb5 >= 1.12: copy this file in /etc/gss/mech.d
#
# Mechanism Name Object Identifier Shared Library Path Other Options
gssntlmssp_v1 1.3.6.1.4.1.311.2.2.10
 /usr/lib64/gssntlmssp/gssntlmssp.so
===


With that, I can then use the examples like this :
./examples/smb2-ls-async smb://sahlberg@10.10.10.11/SNAP1

and it will authenticate as sahlberg and use the password in the NTLM file
above.


If I want to, I can also "authenticate" as a guest.
To do that I need to make sure that the share is set up with "guest ok" in
the samba server:
===
[SNAP1]
  path = /data/SNAP-1
  read only = yes
  guest ok = yes
===

Then I can just pass a non-existing username/any name and it will still
have access. That user soe not even hve to be in the NTLM file above even.
./examples/smb2-ls-async smb://KODI@10.10.10.11/SNAP1

To get guet accesss on windows, you should set the share and give the
"Everyone" group access to the share.

Let me know how that goes...

regards
ronnie sahlberg

**Comment by lrusak** [comment]
ok I got it. I was just missing the NTLM_USER_FILE. This file cannot be blank and needs at least
```
WORKGROUP:guest:
```
