### ISSUE TITLE
Support for signing added: https://github.com/simo5/gss-ntlmssp/pull/3

### ISSUE THREAD

**Issue by amandeepgautam** [sahlberg/libsmb2#121]
We should be able to support signing using krb5 library with the plugin after the pull request is merged: https://github.com/simo5/gss-ntlmssp/pull/3.

Maybe we would need to update the documentation.

P.S.: Please let me know if there are better channels for communicating messages like these.

**Comment by sahlberg** [comment]
Once the patch lands in gss-ntlmssp  please send me a pull request with an update to the README file.

**Comment by amandeepgautam** [comment]
@sahlberg The patch is now merged. I will update the readme and send a pull request.

**Comment by amandeepgautam** [comment]
@sahlberg Updated the pull request.
