### ISSUE TITLE
Why clamp read/write size in library when large pdu is not supported

### ISSUE THREAD

**Issue by amandeepgautam** [sahlberg/libsmb2#122]
I am trying to understand the rationale behind the commit: https://github.com/sahlberg/libsmb2/commit/3f3976a2e3d50c6800be8d968e9f8d971fa37ca4.

In our case, we see that on creating a connection to NetApp we get the max read/write size from the server to be 64KB. If the size of the file being read is less than 64KB, we would create compound pdu(open, read and close) for efficient read and saving roundtrips to the server. However, it seems like the library reduces the size further to 60KB. What is the rationale for this and why we cannot rely on server max read/write size?

Also, I should add that I tested by modifying the read size to 64KB(instead of 60KB) and read works fine with the NetApp in our case.

**Comment by sahlberg** [comment]
You are right.
I mis-read this and thought that the credits were based on the size of the whole request
and thus cut it down to 60k since that would be a nice multiple of 4kb.

But I see now that the credit consumption only applies to the variable part of the request/responses.

Do you want to send me a pull request where you fix this bug and set it to 64kb instead ?

**Comment by amandeepgautam** [comment]
@sahlberg  Sure. Will be happy to send a pull request. Another question though: Why 64KB? Why not cap it using a function of max_read_size/max_write_size which sever sends? I am just thinking out loud here and do not have researched how this could be achieved.

**Comment by sahlberg** [comment]
64kb is a hard limit in the protocol itself when you don't have credit support.

**Comment by amandeepgautam** [comment]
@sahlberg I was reading about this and came across this: https://blogs.msdn.microsoft.com/openspecification/2009/04/10/smb-maximum-transmit-buffer-size-and-performance-tuning. It does talk about 60Kb being the max read/write possible but the article itself is very old. Is this still valid?

**Comment by sahlberg** [comment]
That is SMB1 so it doesn't apply here.

**Comment by amandeepgautam** [comment]
@sahlberg okay. Did not realize that it was for SMB1 (the doc didn't mention). I have raise a PR request. Please accept.
