### ISSUE TITLE
Support for smb3

### ISSUE THREAD

**Issue by felixRajkumar** [sahlberg/libsmb2#127]
Will libsmb2 provide complete support for smb3 ie Multichannel and AESEncryption

**Comment by sahlberg** [comment]
It has basic support for SMB3 but not multichannel.
It supports AES128CCM but not AES128GCM.

Multichannel and AES128GCM may be implemented in the future but is not a priority at this stage,

**Comment by felixRajkumar** [comment]
Thanks for the reply, May I know what will be the features that are available in next stage? @sahlberg

**Comment by sahlberg** [comment]
3.1.1 negotiation has been added.  That is how far as I plan to go with smb3 support.
I have no plans got aes128gcm since the required vector instructions to make it meaningful would make the library less portable.
Similarly, multichannel is not a target at this point.
