### ISSUE TITLE
Support for Windows?

### ISSUE THREAD

**Issue by felixRajkumar** [sahlberg/libsmb2#129]
Whether the examples given in the repository is written only for posix or for windows also?

**Comment by sahlberg** [comment]
The library itself compiles and works under Linux/Windows/OSX/iOS/Android,BSD,watchOS/..., and a bunch of real-time embedded systems like ESP32.

It should work on pretty much anything that has a basic libc available with malloc/free/and berkley socket support.

The examples possibly only compile under linux/posix  but these are really just examples to show the API, not to be thought of as actual utilities.
See the examples as short code snippets to show how to use parts of the API but don't depend on them compiling on your platform. They are code examples/snippets, not portable full utilities.

IF however you send me patches to make the examples work on platforms where they currently don't, then of course I will gladly accept and merge those changes.

**Comment by sahlberg** [comment]
I think it would be trivial for you to adapt the example code to windows.
Please see for example the examples in the libnfs repository.


You mainly just need to initialize the bsd sockets from your app under
win32/64 and it should work, like so

#ifdef WIN32
if (WSAStartup(MAKEWORD(2,2), &wsaData) != 0) {
fprintf(stderr, "Failed to start Winsock2\n");
exit(10);
}
#endif
