### ISSUE TITLE
smb2_lseek behaviour is different from nfs_lseek

### ISSUE THREAD

**Issue by lrusak** [sahlberg/libsmb2#13]
I'm not sure if this was intended but it seems that libsmb2 is missing a `current_offset` argument. This is used by Kodi to get the current position. see, https://github.com/xbmc/xbmc/blob/master/xbmc/filesystem/NFSFile.cpp#L519-L534

libsmb2
```
int smb2_lseek(struct smb2_context *smb2, struct smb2fh *fh,
               int64_t offset, int whence);
```
lbnfs
```
EXTERN int nfs_lseek(struct nfs_context *nfs, struct nfsfh *nfsfh,
                     int64_t offset, int whence, uint64_t *current_offset);
```

**Comment by sahlberg** [comment]
Fixed. It now has the same signature as in libnfs
