### ISSUE TITLE
Cut and paste error?

### ISSUE THREAD

**Issue by SwarmSysUser** [sahlberg/libsmb2#134]
While porting to an RX 32 bit MCU with lwIP I found line 933 of libsmb2\lib\dcerpc.c should be:
struct dcerpc_pdu *pdu = (struct dcerpc_pdu*)((char *)__mptr - offsetof(struct dcerpc_pdu, rsp));

**Comment by sahlberg** [comment]
You are right.  It should be harmless but I have fixed the invalid cast.

Thanks. Fix has been pushed.
