### ISSUE TITLE
missing smb2_truncate

### ISSUE THREAD

**Issue by lrusak** [sahlberg/libsmb2#14]
libnfs has nfs_truncate
```
EXTERN int nfs_truncate(struct nfs_context *nfs, const char *path,
                        uint64_t length);
```
A similar function seems to be missing from libsmb2

**Comment by sahlberg** [comment]
I have checked in support for smb_truncate[_async]

It was a little more work than I thought since it seems I never implemented the SMB2 SET_INFO command. :-)

**Comment by lrusak** [comment]
Awesome thanks!

are you able to implement smb2_ftruncate aswell?
