### ISSUE TITLE
Regression due to commit: " We can not access cb_data when status is CANCELLED"

### ISSUE THREAD

**Issue by amandeepgautam** [sahlberg/libsmb2#140]
With commit: https://github.com/sahlberg/libsmb2/commit/5c4d6db14ce4048b7d08d9af3307022ba4992833, we will lose callbacks in the async case, so it is not ideal.

The problem which this commit try to fix is in the sync api because in the sync api's cb_data is allocated on the stack. Ideally, if someone wants to prematurely(cancel) get out of the sync api, they should cancel pending pdus which in turn will make the wait_for_reply function return. If that seems acceptable, I would like to rever this change.

**Comment by sahlberg** [comment]
On Fri, Apr 17, 2020 at 7:32 AM Aman Deep Gautam <notifications@github.com>
wrote:

> With commit: 5c4d6db
> <https://github.com/sahlberg/libsmb2/commit/5c4d6db14ce4048b7d08d9af3307022ba4992833>,
> we will lose callbacks in the async case, so it is not ideal.
>
> The problem which this commit try to fix is in the sync api because in the
> sync api's cb_data is allocated on the stack. Ideally, if someone wants to
> prematurely(cancel) get out of the sync api, they should cancel pending
> pdus which in turn will make the wait_for_reply function return. If that
> seems acceptable, I would like to rever this change.
>

I think you are right.
Do you want to send me a patch that fixes it properly?

**Comment by amandeepgautam** [comment]
@sahlberg Can I send a revert for this. I do not have the bandwidth as of now to send cancellation related CL. Would that be acceptable? Also, could you please reply to the other PR which I have opened: https://github.com/sahlberg/libsmb2/pull/139.

**Comment by sahlberg** [comment]
Yes, you can do that and I will revert it.  I will look at doing the proper
fix too, but since this is just for the SYNC API
it is not super high priority.   IMHO no one should really ever use the
sync api unless for absolutely trivial applications.

**Comment by sahlberg** [comment]
I have done the changes and pushed to master.

Thanks.
