### ISSUE TITLE
The libsmb2 libraries don't support multi-threading

### ISSUE THREAD

**Issue by wangzhhbj** [sahlberg/libsmb2#142]
The libsmb2 libraries don't support multi-threading.
Is there any plan to support multi-threading?
Lock while reading and writing socket.

@sahlberg

**Comment by sahlberg** [comment]
No plans to add multithreading.
This is non-blocking eventdriven library that targets some very low-end platforms where you don't really have a process concept and thus no thread support.

However, as the library is guaranteed to be non-blocking (except smb2_service()  which may block inside application provided callbacks) this should not be an issue.

If you need to use it from a multithreaded application there a a few ways to deal with this:
* you could design the application to only access the smb2_context from a single thread
* or just put a mutex around each call to the smb2_*() functions so you only enter the library from one thread at a time. In this case be careful so you don't call into the library again from the context of one of your callbacks or you will risk a deadlock.

**Comment by wangzhhbj** [comment]
Hey:


Are you a member of the samba team.
I found a bug about samba-ctdb, but my mail delivery failure.(bugzilla-maintenance@samba.org)








At 2020-04-27 13:59:21, "Ronnie Sahlberg" <notifications@github.com> wrote:

No plans to add multithreading.
This is non-blocking eventdriven library that targets some very low-end platforms where you don't really have a process concept and thus no thread support.

However, as the library is guaranteed to be non-blocking (except smb2_service() which may block inside application provided callbacks) this should not be an issue.

If you need to use it from a multithreaded application there a a few ways to deal with this:

you could design the application to only access the smb2_context from a single thread
or just put a mutex around each call to the smb2_*() functions so you only enter the library from one thread at a time. In this case be careful so you don't call into the library again from the context of one of your callbacks or you will risk a deadlock.
