### ISSUE TITLE
smb v1

### ISSUE THREAD

**Issue by DemianSteelstone** [sahlberg/libsmb2#144]
Does this library support smb1?

**Comment by amosavian** [comment]
SMBv1 is old and has been removed/disabled from almost all new operating systems.

You can use [libdsm](https://github.com/videolabs/libdsm) library for SMBv1 or [TOSMBClient](https://github.com/TimOliver/TOSMBClient) for Apple OSes.

**Comment by DemianSteelstone** [comment]
Thanks!
