### ISSUE TITLE
Intermittent problem writing data

### ISSUE THREAD

**Issue by timmeh87** [sahlberg/libsmb2#145]
I seem to get a problem periodically when trying to write data to a CentOS SMB server that is attached to the network via a crappy USB 2.4GHz wifi adapter. After a long time (days) of working normally, writes will begin to fail. I can open contexts okay, only writes fail, so I end up with an empty 0-byte file because opening the file for writing was successful.

If I access the same SMB share via Windows Explorer (all of this is on Windows) I can add, delete, edit files like normal, there does not seem to be an actual problem with the SMB server. But with libsmb2, I cannot wite anything until I unplug the wifi adapter and then plug it back in. Then libsmb2 works again.

The error it gets when writing is 
> Read/Write failed with (0xc000000d) STATUS_INVALID_PARAMETER

The file handle and ctx appears to be valid since at this point an empty file has already appeared in the place where I am writing to. But no mater how many times I try to run the code (connecting fresh each time) I cannot write anything.

I dont have a stack trace because there is no crash (libsmb2 just returns an error) but I did some tracing on my own...

When trying to write data, the code seems to go through the loop inside "wait_for_reply()" twice. The first time it does a write operation and the amount of time it takes suggests that it has actually written some part of the data (120 megabytes) that it is supposed to write (or else it has timed out on that operation?). Regardless, it pauses for about 1-2 seconds on the write operation, and then the second time it goes into "smb2_service()" it produces the error.

On the second time it goes into smb2_service, it is processing a read operation. It makes its way inside "smb2_read_data()", and passes through "read_more_data:" several times. It gets spl (=73), It reads 64b for the header (payload_offset=68, credits=161, status=0xc000000d), it reads 8b more, It makes it to case SMB2_RCV_FIXED and does not directly trigger any errors, then it goes to "read_more_data:", and that next read gets an error code  at this line

`int res = WSARecv(sock, (LPWSABUF)iov, nvecs, &ret, &flags, NULL, NULL);`

it then gets to
`pdu->cb(smb2, smb2->hdr.status, pdu->payload, pdu->cb_data);`

this callback is set to "write_cb()", so it goes there with the value of "status" = 0xc000 000d
which stands for "STATUS INVALID PARAMETER" in windows and  it writes the error string

I dont know enough about this to solve the issue. It looks like the 0xc000 000d  error comes from the header of the "smb thing" it tries to read after writing the data. But then the code does not detect it until it comes up again later when trying to do a WSARecv. 

If you want me to try to get some more info, let me know

**Comment by timmeh87** [comment]
I have an update already. This time after resetting the linux machine, the error I got changed to POLLERR. I still cannot write the 120 megabyte file. However if I try to write a much smaller (150k) file, it works fine. So now I dont even know what to think, I swear that once I was able to write the larger 120mb file successfully. 

Anyways this is still a problem. Why does the exact same code write a 150k buffer but not a 120mb buffer?

```
		smb_fp_out = smb2_open(out_ctx, p.string().c_str(), O_CREAT | O_BINARY | O_WRONLY);
		smb2_write(out_ctx, smb_fp_out, buf.data(), buf.size());
		smb2_close(out_ctx, smb_fp_out)
```;

After successfully creating a new folder with code that is not shown, the "smb2_open" line always creates a new empty file, but given a "buf" which contains either 120mb or 150kb of data, it only writes it if it is 150kb. 120mb fails with "POLLERR" but I swear earlier today it was failing with 0xc000000d on a read.

**Comment by timmeh87** [comment]
one more thing before bed:
Now when I call "smb2_write()" with 120 megabytes it takes a long time to execute, about 13-16 seconds (different each run). I tested in Windows Explorer, and it takes 45 seconds to copy the file. So maybe it is copying some of the data and failing part way through?
Before restarting the computer (in my first post) It was taking 1-2 seconds to complete the write operation which is also too short to transmit the file but still suspiciously long. 

I can write a 5mb file without problems. Is there a max amount of bytes I can write at one time to a file handle? I can break this down into smaller size writes if I have to

also the error text I get right now is
>  "smb2_service failed with : smb2_service: POLLERR, Unknown socket error.\n"

**Comment by sahlberg** [comment]
One of the things that are happening is that you are not checking the
return from smb2_write().
In these cases the write will be short since we will likely clamp it to the
maximum that the server has told us
it can handle in a single SMB2_WRITE operation :
https://github.com/sahlberg/libsmb2/blob/71d9b71c351ea444556f9612f32ee0579f8585a9/lib/libsmb2.c#L1288

So you have to do the usual write() loop you always need in posix :
   while ( count > 0) {
        rc = smb2_write()
        check rc for error
        update buffer pointer
        decrease count
    }

Still though, there is a bug in the libsmb2 code too.
We compute the number of credits we need just a few lines earlier using the
original value for "count".
This computation needs to be done after we possibly do the clamping.
I will fix this bug here, and also I suspect there is a similar bug for
smb2_pread.

**Comment by timmeh87** [comment]
thank you for your reply. i had a feeling i had to do the write in chunks
as you have said. but then the file should still close out with more than
zero bytes right? I guess that is the problem you want to fix so I will
wait for that fix.

also i did fork the code to handle the other issue (winsock init error
message). i was going to try to make a PR today

also i dont want to totally derail this issue but i have another question,
i keep forgetting to check if my file handle is NULL before calling
operations like open, read, write, close. In that case the code throws a
nullptr exception. I would prefer if the functions either returned an error
code or threw a more catchable exception (for example std::runtime
exception). i think this lib prefers error codes which is fine. just the
nullptr exception is uncatchable and causes the program to halt. i am
willing to add a simple pointer check to the asynch functions if you
approve of the idea. i think the most appropriate code is EINVAL

**Comment by sahlberg** [comment]
On Fri, Jun 12, 2020 at 3:52 AM timmeh87 <notifications@github.com> wrote:

> thank you for your reply. i had a feeling i had to do the write in chunks
> as you have said. but then the file should still close out with more than
> zero bytes right? I guess that is the problem you want to fix so I will
> wait for that fix.
>
> also i did fork the code to handle the other issue (winsock init error
> message). i was going to try to make a PR today
>
> also i dont want to totally derail this issue but i have another question,
> i keep forgetting to check if my file handle is NULL before calling
> operations like open, read, write, close. In that case the code throws a
> nullptr exception. I would prefer if the functions either returned an error
> code or threw a more catchable exception (for example std::runtime
> exception). i think this lib prefers error codes which is fine. just the
> nullptr exception is uncatchable and causes the program to halt. i am
> willing to add a simple pointer check to the asynch functions if you
> approve of the idea. i think the most appropriate code is EINVAL
>

O, absolutely. We should not crash if a NULL ptr is passed in to these
functions. That is a bug.
Please add checks that if the pointer in NULL then it returns -EBADF (or
-EINVAL)
and send a pull request.

**Comment by timmeh87** [comment]
Hello, I have tested the commits you made recently, and my problem with writing a large file is now fixed. For reference, here is the working code:

```
smb_fp_out = smb2_open(out_ctx, p.string().c_str(), O_CREAT | O_WRONLY);
int loc = 0;
while (loc < buf.size())
{
	int res= smb2_write(out_ctx, smb_fp_out, buf.data() + loc, buf.size() - loc);
	if (res > 0)
	{
		loc += res;
	}
	else
	{
		printf("error writing to smb: %d\n", res);
	}
}
smb2_close(out_ctx, smb_fp_out);
```

the difference is that after I call smb2_write(), it actually writes 8192 bytes instead of zero bytes. I think you can close the issue
