### ISSUE TITLE
make clean sometimes failed for PS2 target

### ISSUE THREAD

**Issue by AKuHAK** [sahlberg/libsmb2#152]
https://github.com/sahlberg/libsmb2/blob/1c7133e03742934c9f499be232d16469b0b4102c/lib/Makefile.PS2_EE#L59

maybe change to `rm -rf`

**Comment by sahlberg** [comment]
Done.

Thanks.

**Comment by sahlberg** [comment]
BTW. I have tested this on a ps2 using a modified "ps2dev/ps2sdk/samples/network/tcpip-basic/" utility.

I also have a build for IOP in the "ps2" branch that I have not been able to test.
(I am new to ps2 and do not yet know how to build applications for iop)

Once I get some one to test and verify the iop build I would be happy to merge it into master.
