### ISSUE TITLE
ESP-IDF CMake error on build

### ISSUE THREAD

**Issue by 11ange** [sahlberg/libsmb2#165]
Hello!
I'm using ESP-IDF v4.1 (ESP32) and I got this error:

  _CMake Error at C:/esp-idf_v41/components/libsmb2/CMakeLists.txt:3
  (project):
    project command is not scriptable_

that refers to:
_project(libsmb2
        LANGUAGES C
        VERSION 3.0.0)_

If I remove those lines, error is now:

  _CMake Error at C:/esp-idf_v41/components/libsmb2/CMakeLists.txt:26
  (include):
    include could not find load file:
      cmake/ConfigureChecks.cmake_

that refers to:
_include(cmake/ConfigureChecks.cmake)_

File exists but compiler did not find it.

I'm using master branch.

Thank you in advance!
Luis

**Comment by adamwilt** [comment]
The top-level CMakeLists.txt is completely wrong for an esp-idf component. Look at my fork: https://github.com/adamwilt/libsmb2. I changed the top-level CMakeLists.txt to work as part of an esp-idf project, and commented out some #defines in portable_endian.h that appear to be unnecessary (see [pull request 191](https://github.com/sahlberg/libsmb2/pull/191)). It seems to be working properly and doesn't appear to break the build process in non-ESP32 environments.

If that pull request isn't integrated into the sahlberg code and that code evolves further, you can always apply the same sorts of edits to your copies of CMakeLists.txt and portable_endian.h.

**Comment by sahlberg** [comment]
Thanks!
I have merged your pull request.
