### ISSUE TITLE
Does not support anonymous login？

### ISSUE THREAD

**Issue by azureplus** [sahlberg/libsmb2#168]

**Comment by sahlberg** [comment]
It does support Anonymous logins for protocol version < 3.1.1, so add a URL argument like vers=3.0 to enable Anonymous support.


Example:
./examples/smb2-ls-sync smb://Anomymous@Server/Share/\?vers=3.0

To request Anonymous login specify a username (Anonymous in the example above, but any name will do) that does NOT
exist in the NTLM_USER_FILE.
In that case libsmb2 will attempt to login with no username at all, i.e. Anonymous.

This was tested against samba and current master of libsmb2.
For windows or other servers you may need to check their documentation on how to enable Anonymous access to shares.

Anonymous and Guest support is best-effort at best here. I don't think we should use this in modern environments so there is no real guarantee or testing that it works in libsmb2 and little effort to maintain it.

Please do not allow Anonymous/Guest access from your server.

**Comment by azureplus** [comment]
> It does support Anonymous logins for protocol version < 3.1.1, so add a URL argument like vers=3.0 to enable Anonymous support.
> 
> Example:
> ./examples/smb2-ls-sync smb://Anomymous@Server/Share/?vers=3.0
> 
> To request Anonymous login specify a username (Anonymous in the example above, but any name will do) that does NOT
> exist in the NTLM_USER_FILE.
> In that case libsmb2 will attempt to login with no username at all, i.e. Anonymous.
> 
> This was tested against samba and current master of libsmb2.
> For windows or other servers you may need to check their documentation on how to enable Anonymous access to shares.
> 
> Anonymous and Guest support is best-effort at best here. I don't think we should use this in modern environments so there is no real guarantee or testing that it works in libsmb2 and little effort to maintain it.
> 
> Please do not allow Anonymous/Guest access from your server.

Thanks,
For home users, when there is nothing important, they like to log in to home network users without password

**Comment by azureplus** [comment]
how to use this  api: smb2_connect_share_async?
