### ISSUE TITLE
Unable to read more than 64k bytes from a file.

### ISSUE THREAD

**Issue by afedchin** [sahlberg/libsmb2#17]
If I read more than 64k bytes from a file (i.e. more than one credit) it causes forcible closing connection by the host on next request.

![image](https://user-images.githubusercontent.com/2063885/37328527-927a7d5a-26ab-11e8-95e3-61490b86894a.png)

![image](https://user-images.githubusercontent.com/2063885/37328547-a53cc5e2-26ab-11e8-93e0-b00b1d044d1b.png)

![image](https://user-images.githubusercontent.com/2063885/37328568-b1856e1c-26ab-11e8-937a-1b1f10e9ce58.png)

**Comment by sahlberg** [comment]
Thanks.

I will have a look at this and the previous issue.

Sorry about this.  It is still very early code :-)
But we will get there.

**Comment by sahlberg** [comment]
Fixed.

I had missed : 
3.2.4.1.5 Sending Multi-Credit Requests
...
Before sending a multi-credit request, the client MUST consume the calculated number of consecutive
MessageIds from Connection.SequenceWindow.

**Comment by afedchin** [comment]
works great. thanks.
