### ISSUE TITLE
Functions to initialize already allocated smb context.

### ISSUE THREAD

**Issue by stefbon** [sahlberg/libsmb2#181]
Hi,

I'm working on a super FUSE fs which mounts SSH/sftp services when
usersessio starts, providing a browseable network map on:

/run/network/$USER/fs

like;

/run/network/sbon/fs/Open Secure Network
Services/bononline.nl/admin/{public, sbon}

In this case two directories on the server admin in domain
bononline.nl are shared using sftp.
In the planning are:
- support for data over UDP using libudt
- support for channels for textchat/videochat with other users
connected to the server admin.
- support for backup, providing access to previous versions of files using FUSE
- support for fsnotify over the network (complicated!)

See:
https://github.com/stefbon/fs-workspace

My construction uses a generic interface to connect and do io with
remote services. For the interface (and the rest of the programm) the
service is a black box.
The interface is allocated with a buffer the size required to hold the
struct of the service (like a ssh session, a ssh channel, a sftp
client).

Now I want to add support for SMB (using libsmb2). There is no
function to get the size of the struct smb2_context, and initialize an
already allocated smb2_context. (The path to this will look like:
/run/network/$USER/fs/Windows Network/ExampleWorkgroup/Server/{shares...}).

It would be great to add such a function.
Do I have to write a patch for that?

Thanks,

Stef Bon
the Netherlands

**Comment by stefbon** [comment]
The way I look at it a function like:

struct smb2_context *smb2_create_context(struct smb2_context *ctx);

will use an already allocated smb2_context and return that if ctx is defined.
If it is not defined it does the same as smb2_init_context(void);
A flag has to be set when the ctx is allocated by libsmb2 and not by the calling context:
if this flag is not set the calling context is responsible for freeeing.

Stef

**Comment by sahlberg** [comment]
On Sun, Dec 20, 2020 at 5:18 AM stefbon <notifications@github.com> wrote:

> Hi,
>
> I'm working on a super FUSE fs which mounts SSH/sftp services when
> usersessio starts, providing a browseable network map on:
>
> /run/network/$USER/fs
>
> like;
>
> /run/network/sbon/fs/Open Secure Network
> Services/bononline.nl/admin/{public <http://bononline.nl/admin/%7Bpublic>,
> sbon}
>
> In this case two directories on the server admin in domain
> bononline.nl are shared using sftp.
> In the planning are:
>
>    - support for data over UDP using libudt
>    - support for channels for textchat/videochat with other users
>    connected to the server admin.
>    - support for backup, providing access to previous versions of files
>    using FUSE
>    - support for fsnotify over the network (complicated!)
>
> See:
> https://github.com/stefbon/fs-workspace
>
> My construction uses a generic interface to connect and do io with
> remote services. For the interface (and the rest of the programm) the
> service is a black box.
> The interface is allocated with a buffer the size required to hold the
> struct of the service (like a ssh session, a ssh channel, a sftp
> client).
>
> Now I want to add support for SMB (using libsmb2). There is no
> function to get the size of the struct smb2_context, and initialize an
> already allocated smb2_context. (The path to this will look like:
> /run/network/$USER/fs/Windows Network/ExampleWorkgroup/Server/{shares...}).
>

So you want to malloc()/free() the context structure from your application
instead of letting libsmb2 do it?
Ok, that is an unusual request and something I suspect few applications
will have a need for,
but it would be very little code to maintain so I don;t see much harm.

So you would basically need a
int smb2_get_context_size()    that basically returns sizeof(struct
smb2_context)
and a second function
int smb2_init_context_existing(struct smb2_context *smb2)
which just fills it in?

Ok, should be a trivial amount of code so please send me a pull request.

Or maybe you want to have a
int smb2_init_context_existing(struct smb2_context **smb2)
which if *smb2 is non-NULL just fills it in but if *smb == NULL also
allocates the struct, i.e. does basically what smb2_init_context() does.

**Comment by stefbon** [comment]
Yes that will do what I request:

int smb2_init_context_existing(struct s,b2_context **smb2).

I will do that when I'm ready doing what has to be finished first (an implementation of a skiplist).

You will hear from me soon I hope. This will the first patch I wll write for a software project owned by somebody else.

Stef

**Comment by stefbon** [comment]
Hi,

I'm been busy doing something else. Last week I started the smb implementation again.
Does closing this issue mean I cannot write the patches anymore?

Stef

**Comment by sahlberg** [comment]
You can, just means I am closing issues I am not going to work on and
looked abandoned
