### ISSUE TITLE
[PS2] cannot compile with latest ps2sdk

### ISSUE THREAD

**Issue by AKuHAK** [sahlberg/libsmb2#184]
When compiling on the latest PS2SDK - received the following error:
`make -f Makefile.PS2_EE install`

```make
ee-gcc -D_EE -O2 -G0 -Wall -DPS2_EE_PLATFORM -DHAVE_STDINT_H -DHAVE_STRING_H -DHAVE_STDLIB_H -DHAVE_SYS_TYPES_H -DHAVE_UNISTD_H -D_U_=/**/ -I/usr/local/ps2dev/ps2sdk/ee/include -I/usr/local/ps2dev/ps2sdk/common/include -I. -I../include -I../include/smb2 -c socket.c -o socket.o
socket.c: In function `smb2_close_connecting_fds':
socket.c:104: `for' loop initial declaration used outside C99 mode
socket.c: In function `smb2_close_connecting_fd':
socket.c:654: `for' loop initial declaration used outside C99 mode
socket.c: In function `smb2_service_fd':
socket.c:680: `for' loop initial declaration used outside C99 mode
socket.c: In function `smb2_connect_async_next_addr':
socket.c:905: `for' loop initial declaration used outside C99 mode
socket.c: In function `smb2_connect_async':
socket.c:1052: `for' loop initial declaration used outside C99 mode
make: *** [/usr/local/ps2dev/ps2sdk/samples/Makefile.eeglobal:31: socket.o] Error 1
Error: Process completed with exit code 2.
```

**Comment by AKuHAK** [comment]
There is also one warning BTW:
```cpp
ee-gcc -D_EE -O2 -G0 -Wall -DPS2_EE_PLATFORM -DHAVE_STDINT_H -DHAVE_STRING_H -DHAVE_STDLIB_H -DHAVE_SYS_TYPES_H -DHAVE_UNISTD_H -D_U_=/**/ -I/usr/local/ps2dev/ps2sdk/ee/include -I/usr/local/ps2dev/ps2sdk/common/include -I. -I../include -I../include/smb2 -c libsmb2.c -o libsmb2.o
libsmb2.c: In function `smb2_derive_key':
libsmb2.c:555: warning: large integer implicitly truncated to unsigned type
```
looks like
uint4_t * 8 = uint32_t looks like there can be overflow

**Comment by sahlberg** [comment]
> When compiling on the latest PS2SDK - received the following error:
> `make -f Makefile.PS2_EE install`
> 
> ```makefile
> ee-gcc -D_EE -O2 -G0 -Wall -DPS2_EE_PLATFORM -DHAVE_STDINT_H -DHAVE_STRING_H -DHAVE_STDLIB_H -DHAVE_SYS_TYPES_H -DHAVE_UNISTD_H -D_U_=/**/ -I/usr/local/ps2dev/ps2sdk/ee/include -I/usr/local/ps2dev/ps2sdk/common/include -I. -I../include -I../include/smb2 -c socket.c -o socket.o
> socket.c: In function `smb2_close_connecting_fds':
> socket.c:104: `for' loop initial declaration used outside C99 mode
> socket.c: In function `smb2_close_connecting_fd':
> socket.c:654: `for' loop initial declaration used outside C99 mode
> socket.c: In function `smb2_service_fd':
> socket.c:680: `for' loop initial declaration used outside C99 mode
> socket.c: In function `smb2_connect_async_next_addr':
> socket.c:905: `for' loop initial declaration used outside C99 mode
> socket.c: In function `smb2_connect_async':
> socket.c:1052: `for' loop initial declaration used outside C99 mode
> make: *** [/usr/local/ps2dev/ps2sdk/samples/Makefile.eeglobal:31: socket.o] Error 1
> Error: Process completed with exit code 2.
> ```

Please try current master branch. I have fixed these issues for the PS2 build.

**Comment by AKuHAK** [comment]
Argh, ps2sdk just updated to GCC v10 1 hour ago:
```make
mips64r5900el-ps2-elf-gcc -D_EE -O2 -G0 -Wall -DPS2_EE_PLATFORM -DHAVE_STDINT_H -DHAVE_STRING_H -DHAVE_STDLIB_H -DHAVE_SYS_TYPES_H -DHAVE_UNISTD_H -D_U_=/**/ -I../include -I../include/smb2 -I/usr/local/ps2dev/ps2sdk/ee/include -I/usr/local/ps2dev/ps2sdk/common/include -I.  -c aes128ccm.c -o aes128ccm.o
In file included from aes128ccm.c:35:
../include/portable-endian.h:27: warning: "_LITTLE_ENDIAN" redefined
   27 | #       define _LITTLE_ENDIAN LITTLE_ENDIAN
      | 
In file included from /usr/local/ps2dev/ee/mips64r5900el-ps2-elf/sys-include/machine/endian.h:6,
                 from /usr/local/ps2dev/ee/mips64r5900el-ps2-elf/sys-include/sys/types.h:49,
                 from /usr/local/ps2dev/ee/mips64r5900el-ps2-elf/sys-include/stdio.h:61,
                 from aes128ccm.c:30:
/usr/local/ps2dev/ee/mips64r5900el-ps2-elf/sys-include/machine/_endian.h:18: note: this is the location of the previous definition
   18 | #define _LITTLE_ENDIAN 1234
      | 
```
```make
mips64r5900el-ps2-elf-gcc -D_EE -O2 -G0 -Wall -DPS2_EE_PLATFORM -DHAVE_STDINT_H -DHAVE_STRING_H -DHAVE_STDLIB_H -DHAVE_SYS_TYPES_H -DHAVE_UNISTD_H -D_U_=/**/ -I../include -I../include/smb2 -I/usr/local/ps2dev/ps2sdk/ee/include -I/usr/local/ps2dev/ps2sdk/common/include -I.  -c compat.c -o compat.o
In file included from compat.c:19:
compat.h:34:16: error: conflicting types for 'rand'
   34 | #define random rand
      |                ^~~~
In file included from compat.c:81:
/usr/local/ps2dev/ee/mips64r5900el-ps2-elf/sys-include/stdlib.h:144:5: note: previous declaration of 'rand' was here
  144 | int rand (void);
      |     ^~~~
make: *** [/usr/local/ps2dev/ps2sdk/samples/Makefile.eeglobal:31: compat.o] Error 1
Error: Process completed with exit code 2.
```
I will try to switch to earlier version of sdk.

**Comment by AKuHAK** [comment]
ps2dev/ps2sdk:v1.2.0
now compiles fine

**Comment by sahlberg** [comment]
I think I have fixed all the issues with the new gcc version, except the one with rand/random
#define random rand

I suspect the new version of gcc now brings in a version of random() so this define should not be needed anymore.
Since this is a function and not a preprocessor symbol I cant fix it by just a simple #ifndef conditional on the symbol itself.

I suspect just removing this line will make it work on the new gcc and gcclib versions. But that is not a good solution.

I will try to install the new version of the toolchain and see if there is a version number or similar #define I can use to conditionally
handle this. So that it will work both for the older toolchains as well as the newer toolchains.

**Comment by AKuHAK** [comment]
Thank you for your effort, but I dont think they you should keep compatibility with older toolchain. The goal is to completely avoid using older toolchain. Libsmb2 can be very useful in 2 biggest ps2 apps: wLaunchELF and Open-PS2-Loader which both are switched into gcc 10. And development on modern version is much easier. I just thought that removing this line will brake compatibility with other platforms, but if this is defined only for ps2toolchain, you can safely keep only gcc10 compatibility.

**Comment by sahlberg** [comment]
I should work now.
