### ISSUE TITLE
Heap corruption on Windows, wrong malloc argument on 64 bit machines?

### ISSUE THREAD

**Issue by delins** [sahlberg/libsmb2#187]
I've written a small test application on windows. In release mode it runs fine, but in Debug mode CRT claims to have detected a heap corruption. The full message is:

> Debug Error!
> Program: ...ld-smbtest-Desktop_Qt_5_15_1_MSVC2019_64bit-Debug\smbtest.exe
> HEAP CORRUPTION DETECTED: after Normal block (#211) at 0x00000202E0146970.
> CRT detected that the application wrote to memory after end of heap buffer.
> (Press Retry to debug the application)

Debugging pointed in the direction of the line `free(smb2->connecting_fds);` in the function `smb2_close_connecting_fds` in `lib/socket.c`. 

`smb2->connecting_fds` is of type `t_socket *`, yet at line 1060 it is initialized with `smb2->connecting_fds = malloc(sizeof(int) * addr_count);`. I changed it to `smb2->connecting_fds = malloc(sizeof(t_socket) * addr_count);` and the CRT heap corruption is gone.

On my system `sizeof(int)` is 4 bytes whereas `sizeof(t_socket)` is 8 bytes, so I'd say the `malloc` allocates less memory than the `free` frees.

There are quite a few places where `t_socket`, `size_t` and `ssize_t` are implicitly converted to an int. I haven't investigated whether these pose a problem as well or whether they're only a source of warnings from the compiler.

**Comment by sahlberg** [comment]
Very good analysis. Thanks for this.

Can you send me a pull request so that you get credit in the git history?
