### ISSUE TITLE
Compiler warnings

### ISSUE THREAD

**Issue by delins** [sahlberg/libsmb2#189]
The compiler spits out quite some warnings about shortening integer types, conversion of WINSOCK to int on Windows, dropping const qualifiers, etc. I'm sure some of these will eventually lead to hard to debug errors.

While looking at these warnings, some things in particular came up:

In `lib/init.c:463` the `case '\n'` statement falls through so that `finished = 1` is always executed on the first iteration. Given the structure of the code I assume this is an error, but if not, it's better to replace it with an if statement to make the intent clear.

In `lib/socket.c:880` the return value of `socket()` is checked with `fd == -1`. Afaik this should be fine on UNIX, but, besides `int` being incorrect to hold the return value of `socket` on windows, `fd` should there be compared to [`INVALID_SOCKET`](https://docs.microsoft.com/en-us/windows/win32/winsock/socket-data-type-2)

I'm reluctant to fix all these warnings since I'm unfamiliar with the code base and don't know whether they might have side effects.

**Comment by sahlberg** [comment]
declaring github issues bancruptcy
