### ISSUE TITLE
Not possible to issue multiple async read requests on a single file handle

### ISSUE THREAD

**Issue by delins** [sahlberg/libsmb2#198]
I wish to do readahead on open `smb2fh` file handles with async reads. This should significantly speed up retrieving a file when accessing it sequentially. 

From looking at a pcap of calling `cp` on a file while the share is mounted in Linux using `cifs`, I see that it does some readahead as well (a read request for a block is sent before the read response for the previous block is received), so it should be possible. This would also explain why sequentially accessing a file through the mount is roughly 20% faster than my test program using libsmb2.

`smb2_pread_async` looks like it could support this use case. And although `smb2fh` has an `offset` attribute, it looks like it's only used in the `smb2_read`, `smb2_write` and `smb2_lseek` commands. I haven't looked much deeper into the code to tell whether some other parts may not support the use case.

Unfortunately, it doesn't seem to be possible to tell two reads apart from each other in the callback of `smb2_pread_async`. According to its documentation:
> When the callback is invoked, status indicates the result:
> \>=0` : Number of bytes read.
> -errno : An error occured.
>
> Command_data is always NULL.

It would be nice if a client could provide `smb2_pread_async`  with an additional argument that is later returned verbatim in the callback. This could be as simple as a 64 bit (unsigned) int. Clients could set it to the offset in the file for which they called the function, or simply an incrementing number (which I would prefer).

Is this something you would willing to implement and/or look into whether it's possible? Or perhaps there's a good reason the function doesn't allow this use case at the moment that I don't see?

**Comment by sahlberg** [comment]
On Wed, Apr 21, 2021 at 1:58 AM delins ***@***.***> wrote:

> I wish to do readahead on open smb2fh file handles with async reads. This
> should significantly speed up retrieving a file when accessing it
> sequentially.
>
> From looking at a pcap of calling cp on a file while the share is mounted
> in Linux using cifs, I see that it does some readahead as well (a read
> request for a block is sent before the read response for the previous block
> is received), so it should be possible. This would also explain why
> sequentially accessing a file through the mount is roughly 20% faster than
> my test program using libsmb2.
>
> smb2_pread_async looks like it could support this use case. And although
> smb2fh has an offset attribute, it looks like it's only used in the
> smb2_read, smb2_write and smb2_lseek commands. I haven't looked much
> deeper into the code to tell whether some other parts may not support the
> use case.
>
> Unfortunately, it doesn't seem to be possible to tell two reads apart from
> each other in the callback of smb2_pread_async. According to its
> documentation:
>
> When the callback is invoked, status indicates the result:
> >=0` : Number of bytes read.
> -errno : An error occured.
>
> Command_data is always NULL.
>
> It would be nice if a client could provide smb2_pread_async with an
> additional argument that is later returned verbatim in the callback. This
> could be as simple as a 64 bit (unsigned) int. Clients could set it to the
> offset in the file which they called the function, or simply an
> incrementing number (which I would prefer).
>
But you can, that is what the cb_data argument to smb2_pread_async() is
for. This can be a structure that contains anything you need in the
callback but also
offset and length if you want to store that too.
cb_data is void* that you provide from the caller to smb2_pread_async()
(and all other async calls) and this pointer will be returned to the
callback as the fourth argument in the callback.


> Is this something you would willing to implement and/or look into whether
> it's possible? Or perhaps there's a good reason the function doesn't allow
> this use case at the moment that I don't see?
>
It was likely omitted since I didn't see a usecase for it since you can
already do this via the private_data pointer you pass to the function and
which is returned in the callback.

But I am not against adding something like this.
Command_data is NULL for these callbacks so we can use that.

Maybe creating a
struct pread_cb_data {
    uint64_t offset;
};

And pass a pointer of it to the callback as command_data?


That should be fairly straightforward to implement. And we should then also
do the same for smb2_pwrite_async.
Do you want to give it a shot and send a pull request for this, and get
credits for the idea and the implementation?

Otherwise I can implement this tomorrow.

**Comment by delins** [comment]
You're right. I somehow overlooked the possibility of using `cb_data` for that as well. Sorry for saying libsmb2 couldn't do something it most definitely can :) I'm already using `cb_data` for something else, and adding an extra wrapper (and storing it etc) just so that it's possible to pass multiple pointers to the callback is something that I'd like to avoid. I think using `command_data` would be a good idea!

Since people most likely will want the `smb2fh` object in the callback of `smb2_pread_async` as well, perhaps we could pass both the `smb2fh` and the offset using the `command_data`? That would free up the `cb_data` parameter for something else.

I think it could be implemented without impacting the code a lot as follows:

```c
struct smb2_rdwr_cb_data {
        struct smb2fh *fh;
        uint64_t offset;
};

struct rw_data {
        smb2_command_cb cb;
        void *cb_data;

        struct smb2_rdwr_cb_data rdwr_cb_data;
};
```

We could even stuff the initially requested count and buffer address into `smb2_rdwr_cb_data`, which would give you back all the stuff you gave to `smb2_pread_async`. But I'll leave that up to you.

Also, I dropped the `p` from the new struct name, since it will also automatically populate the command_data of the callback in `smb2_read_async` and `smb2_write_async` as well, if I'm not mistaken. Now it's more generic.

If we know what we want here I can create a pull request, no problem.

**Comment by sahlberg** [comment]
On Wed, Apr 21, 2021 at 8:41 PM delins ***@***.***> wrote:
>
> You're right. I somehow overlooked the possibility of using cb_data for that as well. Sorry for saying libsmb2 couldn't do something it most definitely can :) I'm already using cb_data for something else, and adding an extra wrapper (and storing it etc) just so that it's possible to pass multiple pointers to the callback is something that I'd like to avoid. I think using command_data would be a good idea!
>
> Since people most likely will want the smb2fh object in the callback of smb2_pread_async as well, perhaps we could pass both the smb2fh and the offset using the command_data? That would free up the cb_data parameter for something else.
>
> I think it could be implemented without impacting the code a lot as follows:
>
> struct smb2_rdwr_cb_data {
>         struct smb2fh *fh;
>         uint64_t offset;
> };
>
> struct rw_data {
>         smb2_command_cb cb;
>         void *cb_data;
>
>         struct smb2_rdwr_cb_data rdwr_cb_data;
> };
>
> We could even stuff the initially requested count and buffer address into smb2_rdwr_cb_data, which would give you back all the stuff you gave to smb2_pread_async. But I'll leave that up to you.

Yeah, why not. I would not cost much to add it there as well, so go for it.

>
> Also, I dropped the p from the new struct name, since it will also automatically populate the command_data of the callback in smb2_read_async and smb2_write_async as well, if I'm not mistaken. Now it's more generic.
>
> If we know what we want here I can create a pull request, no problem.

I think this sounds like a good suggestion and it would be useful so
please send me a pull request.
