### ISSUE TITLE
Running out of credits when doing lots of IO & handling that situation

### ISSUE THREAD

**Issue by delins** [sahlberg/libsmb2#199]
When I perform a large number (eg >50) of large asynchronous reads (1MB chunks), `smb2_context` often quickly reach 0 credits. When that happens, `smb2_pread_async` sets `count` to `0`, and then happily proceeds to send the smb server a request for 0 bytes. Naturally, in the callback the `count` parameter will also be `0`. `count == 0` is supposed to signal that we reached the end of file, but in this case it was caused by a lack of credits.

Therefore, I think `smb2_pread_async` should return an error right away if it's run out of credits and cannot even get 1 byte. The same probably applies to other flavours of reads and writes, and possibly just all functions. I haven't looked into that.

Related to that: it makes sense that we run out of credits if we send too many large requests simultaneously. But I think there's a bug that delays requesting new credits. Lets say I perform 50 reads. My pcaps show that even though the read requests have the credit charge field correctly set to 16, they only request 1 credit. I then call `smb2_service`, receive control in the callbacks and perform the next reads. These reads also have their credit charge correctly set to 16, but request around 1000 credits.

What I think happens here: libsmb2 always tries to have `MAX_CREDITS` credits. This is achieved with 

```c
hdr->credit_request_response = MAX_CREDITS - smb2->credits; // pdu.c:116
```

However, at this point `smb2->credits` hasn't been decremented with the number of credits this request takes. `smb2->credits` is only decremented after `smb2_service` has been called. Specifically, here:

```c
smb2->credits -= pdu->header.credit_charge; // socket.c:273
```

ie, too late for the request to know it needs to request more credits in order to compensate for the ones it takes. This may also result in reusing credits? Not sure.

One solution could be something like

```c
/* Adjust credit charge for large payloads */ // smb2-cmd-read.c:126
if (smb2->supports_multi_credit) {
        pdu->header.credit_charge = (req->length - 1) / 65536 + 1; // 3.1.5.2 of [MS-SMB2]
        // the cifs kernel driver requests 17 credits in a requests that has a charge of only 16. Perhaps it just likes to hoard them? I don't know. I've copied the behaviour here though.
        if (pdu->header.credit_request_response < pdu->header.credit_charge + 1) {
                pdu->header.credit_request_response = pdu->header.credit_charge + 1;
        }
}
```
I think this should then happen to all `smb2-cmd-*` files. Also, I don't exactly know what the role of `hdr->credit_request_response = MAX_CREDITS - smb2->credits;` will then be. Another solution could be to decrement `smb2->credits` much earlier, somewhere before `hdr->credit_request_response = MAX_CREDITS - smb2->credits;` happens.

I don't have time to look into it further, analyse what the best solution would be and test it all. If you could look into it that would be great!

**Comment by sahlberg** [comment]
declaring github issues bancruptcy
