### ISSUE TITLE
Releasing on the iOS App Store

### ISSUE THREAD

**Issue by TimOliver** [sahlberg/libsmb2#20]
Greetings Ronnie!

I randomly found this library from discussions on the [libdsm](https://github.com/videolabs/libdsm) repo about SMB client libraries that support version 2 and up. This library looks absolutely fantastic!

I've been working on an app for iPhone and iPad and one of my dream features is adding SMB2 support so I can easily access files on my NAS over WiFi directly from the device. I wrote a wrapper around libdsm so it could be built and deployed on iOS devices, however libdsm only supports SMB1 at the moment, and given how different the two protocol standards are, I'm not sure if libdsm will ever get SMB2 support.

I'm curious to try building and deploying libsmb2 for iOS, but before that, I thought I'd better ask you. 

While being able to dynamically link frameworks on iOS solves most of the conditions of the LGPL, the fact that customers can't easily replace the dynamic framework on their devices themselves means shipping LGPL software on the iOS App Store is still somewhat ambiguous. From what I've seen, it usually depends on the original author's views of the LGPL.

What would your thoughts be on this? Would it be acceptable to use this library in shipping iOS software? Or would you prefer not?

Thanks for your time!

**Comment by sahlberg** [comment]
Hi Tim.

I am not a lawyer, so don't put any legal value on what I say, but some people think that LGPLv2.1 is compatible with the app store. See for example https://lwn.net/Articles/526355/
So for pure legal advice I would suggest you talk to your lawyers to get a definitive answer.

That said, I can say what I believe. I think the licence allows use on the app store and I want people to use my library, on as many platforms as possible.

Do you want to use my libsmb2 and ship it on the iOS app store?
Please go ahead.
I would be delighted. I would very much enjoy using applications with AMB2 support from my iPhone devices!

What app are you working on, for my curiosity?

**Comment by TimOliver** [comment]
Hi Ronnie! Thanks for your very prompt reply!

Oh cool! Thanks for the link! I hadn't seen that one before. That certainly adds fuel to the fire.

Yeah! I'm building an app called [iComics](http://icomics.co) which is a DRM-free comic reader app for iOS. Since the users supply the comic files themselves, my main focus now is trying to make it as easy as possible to connect to external devices / services straight from the app itself. I store all of my comic files (Mainly ones I bought from HumbleBundle and comixology) on a Synology NAS in my home, so SMB is the most appropriate way to get at them.

So in that regard, yes, I was wanting to see if it was okay for me to try and build libsmb2 for iOS and ship it in my app. :)

Yay! Excellent! Thank you so much! Okay, when I get the chance then, I'll see if I can create a small prototype to see how easy it is to deploy to iOS and then interact with it from an iOS app level. I'll let you know how I go. :)

Thanks again!

**Comment by sahlberg** [comment]
Tim,

Right now libsmb2 builds on unix/linux and native windows.
There is still some trivial work to be done to build on osx, android and ios.
There are folks, I think, working on this already.

If you want to take on doing some portability work, that would be awesome and I am happy to check any
pull requests.
I think the main areas of concern for iOS would be
* header files. make sure that headers that are needed on ios are included and headers that are not
  available on ios are #ifdef-ed out
* there could well be endianess issues as well.

We fix the bugs and improve portability one patch at a time and we will end up with a really good smb2 client.

**Comment by amosavian** [comment]
@sahlberg I successfully build libsmb2 on iOS, it's now okay. Build scripts are included.

https://github.com/amosavian/AMSMB2

**Comment by sahlberg** [comment]
Cool.

Is this something that would be useful for other iOS developers too? I
guess it might be.

If so you are more than welcome to send me a pull request for
libsmb2/README that adds a small blurb about your swift wrapper.

**Comment by amosavian** [comment]
I will send a PR.

Yes it's a framework that can be easily dragged into Xcode. I've precompiled libsmb2 but user can rebuild it by scripts included.

For now it only supports iOS but macOS and tvOS can be supported with some modifications in build scripts.
