### ISSUE TITLE
Should client disconnect when we get: failed to parse response from server

### ISSUE THREAD

**Issue by amandeepgautam** [sahlberg/libsmb2#205]
Hi,
   This is not an issue, but more of a question. It is about the following error:

```
Failed to parse variable part of command payload
```

I have seen this happen a few times, but I am sure of how to reproduce this consistently. So, wanted to understand what can be the potential reasons for such case. Can this be network errors? Does it make sense for the client to disconnect if this error happens as a fail-safe?
If so, the library would need to differentiate by returning different values from "smb2_service". I would be happy to send a patch if attempting to disconnect is the right thing to do to minimize leaking connections.

**Comment by sahlberg** [comment]
declaring github issues bancruptcy
