### ISSUE TITLE
Adding chown functionality to SetInfo request

### ISSUE THREAD

**Issue by lilybhattacharjee5** [sahlberg/libsmb2#206]
Hello!

A partner and I are working on an internship project that involves using this library in C++ examples that are similar to the library-provided C ones in examples/. One of the functionalities we've implemented is chown for files and directories (seems to be working on our Win32 dev machine, but we need to test more rigorously), and we modified https://github.com/sahlberg/libsmb2/blob/6db01380d882a0ca1e4100f285c18c9e06df5585/lib/smb2-cmd-set-info.c#L52 for that because we noticed encode_set_info request didn't seem to support it currently.

Because of the library LGPL license we were wondering if:
- is this a functionality that you were already planning to add to the library, or does it not belong here?
- is it ok if we make a PR with the chown addition sometime in the next few weeks? (our company is ok with us sharing this code)
- should we add tests / C examples?
- before a PR is merged, is the procedure basically that the new code needs to pass the build checks / be approved by a reviewer? is anything else necessary?

Thank you.

**Comment by sahlberg** [comment]
declaring bug bankruptcy
