### ISSUE TITLE
Unicode conversion bug with UTF-16 surrogate pairs

### ISSUE THREAD

**Issue by delins** [sahlberg/libsmb2#207]
The library has conversion functions between UCS-2 and UTF-8, but as far as I can see there is no UCS-2 in SMB3. [All unicode is encoded in UTF-16LE](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-cifs/d13dd8de-2504-4254-9f81-e351fc5baacd). Perhaps a remnant of the past?

This is generally not an issue, unless names contain code points that require UTF-16 surrogate pairs. That is, all code points >=0x10000. The conversion code doesn't create an error but silently returns the wrong result.

**Comment by sahlberg** [comment]
Yes, it is simplified and can not handle those codepoints.
It is good enough for most usecases but could be improved.

Do you want to try implementing a patch to add better support?

**Comment by delins** [comment]
Sure.

Are `ucs2_to_utf8` and `utf8_to_ucs2` only ever called once all data is available, or are they called in a streaming fashion as well? For instance, if the UTF-16LE string were to be passed to `ucs2_to_utf8` in chunks I'd have to pay extra attention to the case where surrogate pairs are split on a chunk boundary.

**Comment by sahlberg** [comment]
On Tue, Jul 27, 2021 at 11:44 PM delins ***@***.***> wrote:

> Sure.
>
> Are ucs2_to_utf8 and utf8_to_ucs2 only ever called once all data is
> available, or are they called in a streaming fashion as well? For instance,
> if the UTF-16LE string were to be passed to ucs2_to_utf8 in chunks I'd
> have to pay extra attention to the case where surrogate pairs are split on
> a chunk boundary.
>

They are only passed whole strings where all the data is available.

**Comment by sahlberg** [comment]
On Wed, Jul 28, 2021 at 6:42 AM ronnie sahlberg ***@***.***>
wrote:

>
>
> On Tue, Jul 27, 2021 at 11:44 PM delins ***@***.***> wrote:
>
>> Sure.
>>
>> Are ucs2_to_utf8 and utf8_to_ucs2 only ever called once all data is
>> available, or are they called in a streaming fashion as well? For instance,
>> if the UTF-16LE string were to be passed to ucs2_to_utf8 in chunks I'd
>> have to pay extra attention to the case where surrogate pairs are split on
>> a chunk boundary.
>>
>
> They are only passed whole strings where all the data is available.
>

So the pairs will never be split up, which should make things easier.
Also, please keep the code as small and simple as possible.  An important
goal with the library is that it should work with
no external dependencies and also work on very constrained platforms where
there might not even be a proper underlying os, like risc-v soc
or say playstation 2 and similar devices.

**Comment by delins** [comment]
Nice.

`UTF-16LE` --> `UTF-8` is done. There are no additional dependencies. The code has unavoidably gotten bigger, but no more than is necessary. 

I've created a simple test suite that tests the output of the code against ICU. Invalid code points are replaced with the replacement character, etc. I'll add the whole test suite with the pull request when I finish the other code as well. Don't worry about the indentation, I'll double that in the end.

```C
static int
utf16_cp_size(const uint16_t *utf16, int utf16_len)
{
    int length = 0;
    const uint16_t *utf16_end = utf16 + utf16_len;
    while (utf16 < utf16_end) {
        uint32_t code = le16toh(*utf16++);

        if (code < 0x80) { // One UTF-16 code unit maps to one UTF-8 code unit
            length += 1;
        } else if (code < 0x800) { // One UTF-16 code unit maps to two UTF-8 code units
            length += 2;
        } else if (code < 0xd800 || code - 0xe000 < 0x2000) { // All other values where we only have one UTF-16 code unit, which always maps to 3 UTF-8 code units
            length += 3;
        } else if (code < 0xdc00) { // Surrogate pair. 
            
            if (utf16 == utf16_end) { // It's possible the stream ends with a leading code unit, which is an error
                return length + 3; // Replacement char
            }

            uint32_t trail = le16toh(*utf16++);
            if (trail - 0xdc00 < 0x400) { // Check that 0xdc00 <= trail < 0xe000
                code = 0x10000 + ((code & 0x3ff) << 10) + (trail & 0x3ff);
                if (code < 0x10000) {
                    length += 3; // Two UTF-16 code units map to three UTF-8 code units
                } else {
                    length += 4; // Two UTF-16 code units map to four UTF-8 code units
                }
            } else { // Invalid trailing code unit. It's still valid on its own though so only the first unit gets replaced and we rewind
                length += 3; // Replacement char
                utf16--;
            }
        } else { // 0xdc00 <= code < 0xe00, which makes code a trailing code unit without a leading one, which is invalid
            length += 3; // Replacement char
        }
    }

    return length;
}


/*
 * Convert a UTF-16LE string into UTF8
 */
const char *
utf16_to_utf8(const uint16_t *utf16, int utf16_len)
{
    int utf8_len = 1;
    char *str, *tmp;

    /* How many bytes do we need for utf8 ? */
    utf8_len += utf16_cp_size(utf16, utf16_len);
    str = tmp = (char*)malloc(utf8_len);
    if (str == NULL) {
            return NULL;
    }
    str[utf8_len - 1] = 0;

    const uint16_t *utf16_end = utf16 + utf16_len;
    while (utf16 < utf16_end) {
        uint32_t code = le16toh(*utf16++);

        if (code < 0x80) { // One UTF-16 code unit maps to one UTF-8 code unit
            *tmp++ = code;
        } else if (code < 0x800) { // One UTF-16 code unit maps to two UTF-8 code units
            *tmp++ = 0xc0 |  (code >> 6);
            *tmp++ = 0x80 | ((code     ) & 0x3f);
        } else if (code < 0xD800 || code - 0xe000 < 0x2000) { // All other values where we only have one UTF-16 code unit, which always maps to 3 UTF-8 code units
            *tmp++ = 0xe0 |  (code >> 12);
            *tmp++ = 0x80 | ((code >>  6) & 0x3f);
            *tmp++ = 0x80 | ((code      ) & 0x3f);
        } else if (code < 0xdc00) { // Surrogate pair
            
            if (utf16 == utf16_end) { // It's possible the stream ends with a leading code unit, which is an error
                *tmp++ = 0xef; // Replacement char
                *tmp++ = 0xbf;
                *tmp++ = 0xbd;
                return str;
            }

            uint32_t trail = le16toh(*utf16++);
            if (trail - 0xdc00 < 0x400) { // Check that 0xdc00 <= trail < 0xe000
                code = 0x10000 + ((code & 0x3ff) << 10) + (trail & 0x3ff);
                if (code < 0x10000) {
                    *tmp++ = 0xe0 |  (code >> 12);
                    *tmp++ = 0x80 | ((code >>  6) & 0x3f);
                    *tmp++ = 0x80 | ((code      ) & 0x3f);
                } else {
                    *tmp++ = 0xF0 | (code >> 18);
                    *tmp++ = 0x80 | ((code >> 12) & 0x3F);
                    *tmp++ = 0x80 | ((code >> 6) & 0x3F);
                    *tmp++ = 0x80 | (code & 0x3F);
                }
            } else { // Invalid trailing code unit. It's still valid on its own though so only the first unit gets replaced and we rewind
                *tmp++ = 0xef; // Replacement char
                *tmp++ = 0xbf;
                *tmp++ = 0xbd;
                utf16--;
            }
        } else { // 0xdc00 <= code < 0xe00, which makes code a trailing code unit without a leading one, which is invalid
            *tmp++ = 0xef; // Replacement char
            *tmp++ = 0xbf;
            *tmp++ = 0xbd;
        }
    }

    return str;
}
```

**Comment by delins** [comment]
Looking at the UTF-8 to UCS2 code again after your comment about code size I now see the reason why you use the same code for both calculating the size and the actual conversion.

I could probably do that with the UTF-16 code as well, if you think the compiled code size would be significantly smaller? My guess is that it's going to be slower though.

**Comment by sahlberg** [comment]
On Fri, Jul 30, 2021 at 1:40 AM delins ***@***.***> wrote:
>
> Looking at the UTF-8 to UCS2 code again after your comment about code size I now see the reason why you use the same code for both calculating the size and the actual conversion.
>
> I could probably do that with the UTF-16 code as well, if you think the compiled code size would be significantly smaller? My guess is that it's going to be slower though.

Leave it as is for now, it is probably only a a few hundred bytes. The
most important thing right now is that it is portable.
For size, the library is quite big already and clocks in ~140kb, which
is very big for many embedded systems.
I have a branch I am working on to reduce object size (optionally
remove most of the error strings, optionally remove crypto,    etc
that brings the size to <40kb   which is much more manageable for
smaller systems with say only 256k or 512k of memory)
If need to I can optimize this for size later.

Before you send a pull request, can you change the // comments to /* */
Some platforms have really old c compilers that cant handle "new" c++
style comnents.

But looks great!  Thanks for your work!
