### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by ePirat** [sahlberg/libsmb2#216]
Given that there was no release in quite a while and especially as #208 was merged, which fixed invalid UTF-8 being returned, it would be useful to have a new release at some point.

Is there anything I can do to help with that or are there any other issues blocking a new release?

**Comment by sahlberg** [comment]
I will make a new release during the holidays.

**Comment by amandeepgautam** [comment]
@sahlberg just wondering if there will be new release will be anytime soon.

**Comment by sahlberg** [comment]
Thanks for reminding me. I will try to make a new release tomorrow.

**Comment by sahlberg** [comment]
I have pushed a new version as libsmb2 4.0.0
