### ISSUE TITLE
Connection taking long for due to timing out krb5 cred request even when ntlm is to be used

### ISSUE THREAD

**Issue by amandeepgautam** [sahlberg/libsmb2#228]
When we try to acquire creds, we ignore the recommendation from the server and try to use SPNEGO. Referring to a TODO here: https://github.com/sahlberg/libsmb2/blob/master/lib/krb5-wrapper.c#L215

The problem which we are facing is that some queries for krb5 cred acquire are taking more than 2 mins and then timing out. This has happened more than a few times.

We tried a fix where we moved the code: https://github.com/sahlberg/libsmb2/blob/master/lib/krb5-wrapper.c#L269-L282 to https://github.com/sahlberg/libsmb2/blob/master/lib/krb5-wrapper.c#L215. However, we lost the SPNEGO headers in this patch and authentication started failing with Netapp. For some reason, Netapp likes the SPNEGO headers in the packets sent over the wire.

Do you have any other suggestion to better fix this TODO? If the patch does not require in-depth protocol knowledge, would be happy to submit a PR for this.

**Comment by sahlberg** [comment]
This should not be an issue anymore. If sec=ntlmssp is used then we will not even attempt to get a krb5 ticket.
