### ISSUE TITLE
Not able to compile libsmb2.a for mac arm64 architecture

### ISSUE THREAD

**Issue by Dharma-Uba** [sahlberg/libsmb2#232]

**Comment by delins** [comment]
Could you post the error messages you run into?

**Comment by rahul-dutt-sharma** [comment]
<img width="794" alt="image" src="https://user-images.githubusercontent.com/20573460/182448310-e46a2714-12d8-4856-bf96-d22deaf199bf.png">

Its expected that the output is arm64 but the output is x86_64

**Comment by rahul-dutt-sharma** [comment]
The above is from https://github.com/amosavian/AMSMB2 build steps

**Comment by delins** [comment]
I think that one is caused by [this line](https://github.com/amosavian/AMSMB2/blob/4394c4db8e28211e999b87e5d16858dc2db607b2/buildtools/autoframework#L41).

**Comment by Dharma-Uba** [comment]
> 
Actually i got the AMSMB2 repo. 
Then run ./build.sh inside buildtools directory. 
But the output libsmb2-macos.a, only compiles for x86_64 architecture. 

Is there any steps that i can follow so that i can compile libsmb2-macos.a for arm64 architecture?

**Comment by rahul-dutt-sharma** [comment]
resolved.

**Comment by sahlberg** [comment]
Do we need to update the instructions in the README file?  If so, can you send a pull request for it?

**Comment by delins** [comment]
The issue is with https://github.com/amosavian/AMSMB2's build system assuming MacOS always runs x86_64, which isn't the case anymore. No need to update anything in libsmb2 I think.

**Comment by sahlberg** [comment]
declaring github issues bancruptcy
