### ISSUE TITLE
AMSMB2

### ISSUE THREAD

**Issue by geofstro** [sahlberg/libsmb2#234]
From the readMe

"macOS, iOS, tvOS, watchOS
---------------------------

You can use AMSMB2 (https://github.com/amosavian/AMSMB2) universal framework 
which incorporates precompiled libsmb2 for Apple devices."

Please take this more as a comment than an issue with libsmb2 itself.

Unfortunately, I've come to the conclusion that AMSMB2 is no longer a viable option for macOS, iOS, tvOS, watchOS.

1/ It is no longer compatible with the latest xCode 14.xx

2/ My own issue #231, I reported here is a problem that appears to lie with AMSMB2 as opposed to libsmb2.

3/ The author of AMSMB2 does appear to have responded to any issues since May 2020.

I hope someone either takes these issues onboard or writes a new Swift wrapper. Unfortunately also, that is beyond my technical capabilities. So in the meantime, I'm looking for alternatives.

**Comment by sahlberg** [comment]
declaring bug bankruptcy
