### ISSUE TITLE
Building shared library (configure --enable-shared ignored)

### ISSUE THREAD

**Issue by NonBozo** [sahlberg/libsmb2#270]
I'd like to build an .so version of libsmb2 (for memory efficiency and to avoid LGPL issues with static linking) but even though 'configure' tells me --enable-shared is available, no shared objects are produced when it is set.

Is there any reason why an .so version is not available/possible?

Thanks

**Comment by sahlberg** [comment]
On Fri, 15 Sept 2023 at 07:22, NonBozo ***@***.***> wrote:

> I'd like to build an .so version of libsmb2 (for memory efficiency and to
> avoid LGPL issues with static linking) but even though 'configure' tells me
> --enable-shared is available, no shared objects are produced when it is set.
>

You don't need --enable-shared. It builds a shared library by default on
linux.
After you build it it will show up as lib/.libs/libsmb2.so.4.0.0

**Comment by NonBozo** [comment]
Thanks! The .so is indeed there as you say - the problem was only that I checked just in lib/, but 'lib/.libs' is where it ends up, and that is hidden by default.

**Comment by NonBozo** [comment]
Closed.
