### ISSUE TITLE
NetBIOS name resolution for hostnames?

### ISSUE THREAD

**Issue by has207** [sahlberg/libsmb2#279]
Maybe a dumb question, but afaict libsmb2 only supports raw IP addresses for connection. Would an nbns implementation be out of place inside this library leaving it to the caller to handle? Or would it make sense to provide an API here to resolve netbios names either by explicitly calling a function inside libsmb2 or libsmb2 attemping nbns resolution before passing the hostname to the networking code?

**Comment by sahlberg** [comment]
Libsmb2 supports DNS names too (and /etc/hosts files on platforms that have them). 
NBNS is more of a SMB1 thing so don't think we want to add it.

**Comment by has207** [comment]
Sorry yes I meant DNS and IPs. FWIW I really like that OPL supports NBNS and always feel kind of dirty configuring SMB connection using raw IPs (and I don't want to bother with DNS for my handful of local machines). But I understand if you want to keep such legacy stuff out of libsmb2. It should be easy enough to add on top for those that need it.
