### ISSUE TITLE
libsmb2 Debian Package

### ISSUE THREAD

**Issue by jmk-foofus** [sahlberg/libsmb2#315]
Hi,

Any objections to a Debian (Kali/Ubuntu) package for libsmb2? I'm new to Debian packaging, but made an initial attempt here: https://github.com/jmk-foofus/libsmb2-debian-package/tree/master/debian.

Please let me know if it's OK to move forward with submitting this or if there is another preferred method to get it into Debian (and ultimately Kali).

Thanks,
Joe

**Comment by Wolf3s** [comment]
> Hi,
> 
> Any objections to a Debian (Kali/Ubuntu) package for libsmb2? I'm new to Debian packaging, but made an initial attempt here: https://github.com/jmk-foofus/libsmb2-debian-package/tree/master/debian.
> 
> Please let me know if it's OK to move forward with submitting this or if there is another preferred method to get it into Debian (and ultimately Kali).
> 
> Thanks, Joe

Pretty nice debian package.

**Comment by alexmyczko** [comment]
Hmmm, I had found this: https://mentors.debian.net/package/libsmb2/

**Comment by Wolf3s** [comment]
> Hmmm, I had found this: https://mentors.debian.net/package/libsmb2/

Does contains a patch file?

**Comment by alexmyczko** [comment]
Yes?

**Comment by Wolf3s** [comment]
> Yes?

Yes there is...

**Comment by alexmyczko** [comment]
I was hoping for a cli tool that can be used with libsmb2 but was disappointed...

**Comment by Wolf3s** [comment]
> I was hoping for a cli tool that can be used with libsmb2 but was disappointed...

I´m reuniting some patches that i found on internet which leads to some ports.

**Comment by sahlberg** [comment]
No objection to putting this in debian from me  but that is more a question for debian package maintainers than me as I am upstream from them
