### ISSUE TITLE
A couple of questions: (mainly SMBv3 traffic generation)

### ISSUE THREAD

**Issue by RidaShamasneh** [sahlberg/libsmb2#322]
- Is this library supported on Ubunto?
- Can it generate an SMBv3 traffic?
- I need a library that has a support for byte range lock and change notification features? I could not see any of these features implemented in this repo? I wonder if repo is ready to accept changes intended to accomplish these features?

**Comment by smbproton** [comment]
I think that all the features mentioned in this thread are supported in the ynq library which is written in C:
https://visualitynq.com/products/ynq/
