### ISSUE TITLE
smb2_lseek breaks on large files

### ISSUE THREAD

**Issue by MrMC** [sahlberg/libsmb2#35]
smb2_lseek returns -EINVAL on error, else the resulting offset. But if the seek is past 31 bits, then the return value flips negative as it overflows an int. While the seek was good, an error will be signaled (neg return value) and a seek failure will result on app side.

1) Either make current_offset pointer parameter mandatory and only return status ( -EINVAL or 0) 
2) Or change the return from int to int64_t, this will not match file->offset (uint64_t) but it has to be signed to signal an error. 1) seems better.

**Comment by sahlberg** [comment]
On Sun, Apr 22, 2018 at 10:10 AM, RootCoder, LLC. <notifications@github.com>
wrote:

> smb2_lseek returns -EINVAL on error, else the resulting offset. But if the
> seek is past 31 bits, then the return value flips negative as it overflows
> an int. While the seek was good, an error will be signaled (neg return
> value) and a seek failure will result on app side.
>
>    1. Either make current_offset pointer parameter mandatory and only
>    return status ( -EINVAL or 0)
>    2. Or change the return from int to int64_t, this will not match
>    file->offset (uint64_t) but it has to be signed to signal an error. 1)
>    seems better.
>
>
I think 2 is the best.
I will fix this and handle all your other pull requests when I return home
from travelling.

Thanks for your bugreports and pull requests !

**Comment by MrMC** [comment]
thx :) no hurry. 
Up and running under tvOS, looks good so far.

**Comment by sahlberg** [comment]
I have pushed a fix.

Thanks for the report.
