### ISSUE TITLE
Api support for SMB_QUERY_FS_SIZE_INFO?

### ISSUE THREAD

**Issue by memecode** [sahlberg/libsmb2#350]
I was looking into the possibility of supporting a call like [statfs](https://man7.org/linux/man-pages/man2/statfs.2.html) in my fuse wrapper that returns information about the filesystem as a whole. Free space etc. I think the libsmb2 function smb2_decode_file_fs_size_info handles the parsing of that into a structure. But that data is not externally visible right? I don't see a way of getting it via the api... maybe I'm wrong.

So maybe we could have a smb2_stat_fs_async(...) that returns the data in smb2_file_fs_size_info?

**Comment by sahlberg** [comment]
smb2_statvfs[_async] should return this.

**Comment by memecode** [comment]
I swear I looked and should've found that. My apologies.
