### ISSUE TITLE
Guest access, failure to connect

### ISSUE THREAD

**Issue by MrMC** [sahlberg/libsmb2#36]
Has Guest access been verified for smb2/3 (built with --without-libkrb5) ? 

Seeing failure to connect and just starting to dig into it.

**Comment by afedchin** [comment]
use `Guest` as user name without password.

**Comment by MrMC** [comment]
Sure that's how one would do it but I asked if it has been verified ?

**Comment by MrMC** [comment]
Guest access verified.
