### ISSUE TITLE
Request for Supporting auth_verifier_co_t auth_verifier

### ISSUE THREAD

**Issue by vxx0** [sahlberg/libsmb2#360]
#### Background

We are currently using your library in our project, and we have encountered a situation where we need support for `auth_verifier_co_t` and `auth_verifier`. These types are critical for our authentication process, and having support for them would greatly enhance our implementation.

#### Request

Could you please consider adding support for `auth_verifier_co_t auth_verifier`? Specifically, we need the following functionalities:

1. **Support for `auth3`:**
    - Some RPC interactions require auth3 authentication to proceed.

Thank you for considering this request. We are looking forward to your positive response.

Best regards

**Comment by sahlberg** [comment]
Is this logged against the wrong library?
SMB2 does not use auth_verifiers or ONC-RPC.

Please re-log against libnfs.
