### ISSUE TITLE
Enable krb5 support for Apple plat

### ISSUE THREAD

**Issue by debugly** [sahlberg/libsmb2#375]
I want to build static libsmb2 binary with Kerberos support for apple ( iOS/macOS/tvOS) plat，what should I do？
Please help me!

**Comment by sahlberg** [comment]
When you build with autotools the static libsmb2.a will be in the lib/.libs/ subdirectory.
You will need to link your application with lib/.libs/libsmb2.a and also the static version of the MIT Kerberos library/libraries.
