### ISSUE TITLE
Memory issue when queuing non-existing directory.

### ISSUE THREAD

**Issue by erikbernsen** [sahlberg/libsmb2#382]
I see an issue with smb2_opendir when querying a non-existent directory. It crashes my app in some situations, but cannot reproduce it in a small example. I did analyse and think I can see what's going wrong. 

In opendir_cb the code detects that the directory doesn't exist:

![image](https://github.com/user-attachments/assets/a12e2905-1dcf-4cf2-a292-0631b7428b6f)

It will go into free_smb2dir which will free dir->cb_data (after a recent fix for a memory leak I think)

Then here it will go to modify the just deleted cb_data in smb2_opendir in sync.c (each path accesses cb_data)

![image](https://github.com/user-attachments/assets/9bc02f24-db11-41ac-8855-85de9c40e95e)

Eventually crashing the application at a later point where it still thinks it can use cb_data. Problem is that if opendir_cb detects something went wrong then smb2_opendir needs to return NULL. But in its current form it cannot get that information from cb_data since that has already been deleted.

In opendir_cb there is a status argument that we should check against being not null. If it's not null we should do something that makes smb2_opendir return NULL. I think ownership transfer of cb_data to smb2dir (as indicated by this comment)

![image](https://github.com/user-attachments/assets/894ed0dc-4558-45c4-835d-fc3a868e0eb8)

should only happen if opendir_cb is called with successful status argument. If status != 0 then ownership stays with smb2_opendir and it's responsible for deleting it.

**Comment by erikbernsen** [comment]
Maybe I'll come with a PR one of the coming days.

**Comment by sahlberg** [comment]
Good analysis.

I think this should be fixed in current master now.
