### ISSUE TITLE
[cmake] cannot disable krb5 or GSSAPI

### ISSUE THREAD

**Issue by michael-doubez** [sahlberg/libsmb2#384]
I need to compile without krb5 or gssapi.  I tried using `-DCMAKE_DISABLE_FIND_PACKAGE_GSSAPI=ON` and `-DCMAKE_DISABLE_FIND_PACKAGE_LibKrb5=ON`. It is working but the source code is still expecting the libraries.

The reason seems to be that `cmake/ConfigureChecks.cmake` detects the `krb5.h`header and defines `HAVE_LIBKRB5`.

Could you please add `SMB2_KRB5_ENABLE` and `SMB2_GSSAPI_ENABLE` options ?
And completely disable related `find()` and `HAVE_`.

I am also in the process of updating the vcpk recipe.
Could you please tag it once it is done ?

If you prefer, I can contribute a change.

**Comment by sahlberg** [comment]
Please if you could send a pull request.
I am not very familiar with CMake (I am an autotools man)

**Comment by michael-doubez** [comment]
Thank you
https://github.com/microsoft/vcpkg/pull/42779
