### ISSUE TITLE
Missing header in android

### ISSUE THREAD

**Issue by Laxy317** [sahlberg/libsmb2#385]
I try to build libsmb2 for android, but get the error `libsmb2/lib/compat.c:366:13: error: use of undeclared identifier 'ENXIO'`.
`ENXIO` is defined in `errno.h` file, but i've found that there had include `errno.h`(or `sys/errno.h`) file in other platforms, except android. So I'm not sure is there some thing missing in my environments or a code issue?

Error message:
<img width="865" alt="截屏2024-12-17 09 33 00" src="https://github.com/user-attachments/assets/b5a2c2c8-288b-4d00-8258-45a143229d60" />
Source code:
```c
#ifdef __ANDROID__
/* getlogin_r() was added in API 28 */
#if __ANDROID_API__ < 28
#define NEED_GETLOGIN_R
#define login_num ENXIO
#endif
#endif
```

**Comment by sahlberg** [comment]
Either add #include <[sys/]errno.h>or
just add a define for ENXIO
inside that ifdef __ANDROID__ block  and send me a pull request.

I don;t build for androind myself so I depend on androind users to test and send pull requests.

**Comment by Laxy317** [comment]
> Either add #include <[sys/]errno.h>or just add a define for ENXIO inside that ifdef **ANDROID** block and send me a pull request.
> 
> I don;t build for androind myself so I depend on androind users to test and send pull requests.

Ok, i'll test and send a pr.

**Comment by sahlberg** [comment]
fix is merged into master
