### ISSUE TITLE
[tag] create tag for new parameters

### ISSUE THREAD

**Issue by michael-doubez** [sahlberg/libsmb2#388]
Hello,

I mistakely though the tag libsmb2-6.1 included https://github.com/sahlberg/libsmb2/issues/384, but is seems it doesn't.

I am trying to update the version on vcpkg: https://github.com/microsoft/vcpkg/pull/42779
The android build were broken but https://github.com/sahlberg/libsmb2/pull/386 fixes it and was merged before this issues.

cf logs: : https://dev.azure.com/vcpkg/public/_build/results?buildId=110599&view=artifacts&pathAsName=false&type=publishedArtifacts

Can you please tag the repository, at least to include PR https://github.com/sahlberg/libsmb2/pull/387 ?

**Comment by sahlberg** [comment]
I created a new tag at current HEAD : libsmb2-6.2
