### ISSUE TITLE
Listing Shares

### ISSUE THREAD

**Issue by amosavian** [sahlberg/libsmb2#41]
Hi,

How can we list available shares on a server?

Thanks a lot

**Comment by stefbon** [comment]
See:

#9 

Stef

**Comment by amosavian** [comment]
Thanks for fast response, do you know any C library that can handle that?

Another question, Is there any `fstatvfs()` equivalent in this library?

**Comment by sahlberg** [comment]
@amosavian   I have added basic statvfs() support to master.

**Comment by amosavian** [comment]
Thanks alot 🙏 ❤️
