### ISSUE TITLE
statvfs() issues

### ISSUE THREAD

**Issue by amosavian** [sahlberg/libsmb2#44]
Hi,

Thanks for fast implementation of `statvfs()`, Here are two issues I found

1. An strange behavior in linux I found when I implemented https://github.com/apple/swift-corelibs-foundation/pull/1250 was `statvfs()` populates `f_frsize` in Linux with correct block size, whereas old-school `statfs()` (in Darwin) function populates `f_bsize`! I suggest you to fill both with same value for the sake of compatibility.

2. `f_blocks` and `a_bavail` are set to `UINT64_MAX` when server doesn't command. Is this expected behavior?

**Comment by sahlberg** [comment]
Fixed the first,
think the second is expected.
