### ISSUE TITLE
SMB3 fails to sign when path is delimited by slash

### ISSUE THREAD

**Issue by amosavian** [sahlberg/libsmb2#46]
HI,

When I try to connect to my macOS smb server which is SMB 3.02, All `/` delimiters in path must be replaced by `\` otherwise the operation will fail with `Failure to add signature` message.

EDIT: This issue is limited to macOS 10.13.4 High Sierra. Windows 10 and Samba on Linux has no issue with dialect 3.02 signing.

**Comment by sahlberg** [comment]
Pushed a fix for this to master. Please test.

**Comment by sahlberg** [comment]
Good analysis.
Can you please send me a pull request for this change so that you get
proper credit in the git log ?

**Comment by amosavian** [comment]
I did further investigation and I noticed you indeed added last error message to the new one and pass it as variadic argument. I thing there is a problem in handling valist in `smb2_set_error()`. Unfortunately I'm novice in C and don't know much about valists in c.

I can say asserting `smb2->session_key_size == 0` is not problem as it is`16`.

By the way, your fixing commit is working as expected.

**Comment by sahlberg** [comment]
The error string is benign and comes from the second SessionSetup during
NTLMSSP negotiation.
Since this is a session setup command and we thus do not yet have a session
key, we can not yet do signing.

I have fixed this in master now so we will not generate a spurios error
string here.

**Comment by amosavian** [comment]
Yes you are right indeed. 

About that `srvsvc` issue I've noticed the file handle would be `nil` when I try opening with write flag. I implemented async opening to get result and it was -13, which is permission denied. Seems I have to use fsctl for share enumerating for macOS otherwise it. would refuse.

Probably the commit you have pushed for this issue was the right one and already resolved underlying issue. Thus I close this issue.

By the way, macOS is not relying on Samba anymore and have its own smb3 server implementation, which you can [find here](https://opensource.apple.com/source/smb/smb-759.40.1/)

**Comment by sahlberg** [comment]
ok,    I will add support for fcntl next weekend.

**Comment by amosavian** [comment]
Thanks. After you implement fsctl, I will try to create a pull request with listing share ability based on my implementation.

**Comment by amosavian** [comment]
@sahlberg listing share issue is not related to ioctl, I guess it's because overwrite flag set by `smb2_open_async()` when I try to open `srvsvc` pipe. 

I will try to reimplement current listing share implementation in C.
