### ISSUE TITLE
[Enhancement] Implementing smb_cmd_fsctl

### ISSUE THREAD

**Issue by amosavian** [sahlberg/libsmb2#47]
Hi

Current implementation does not support `FSCTL` commands. We need it for two main purposes:

1. **Enumerating shares**: while I successfully [implemented listing shares](https://github.com/amosavian/AMSMB2/commit/70bba0a8f98a9f88305152320e7802f0cfe55fe8) using file interface, official way to support this capability is to use `FSCTL_PIPE_TRANSCEIVE` (0x0011c017) command.
    * Listing shares on macOS 10.13 SMB3 server throws `Failure to add signature` error, similiar to #46.

2. **Server-side copy**: Currently we have to download then upload data to copy a file. With `FSCTL_SRV_COPYCHUNK` & `FSCTL_SRV_COPYCHUNK_WRITE` commands we can duplicate folder/file on server without roundtrip [see details](https://msdn.microsoft.com/en-us/library/cc246740.aspx).

**Comment by amosavian** [comment]
Sorry I've found out that `Failure to add signature` error is not related to listing and is thrown before trying to open file `srvsvc`

**Comment by amosavian** [comment]
I found the issue with `srvsvc` on listing share names. No need to implementing fsctl, just implement a `smb2_open_async()` variation that open file with exactly [this create request settings](https://msdn.microsoft.com/en-us/library/cc246794.aspx). Maybe by introducing a new open flag.

**Comment by sahlberg** [comment]
Sounds good.  Add a new flag and make sure it does not collide with any of
the flags that either exist in libsmb2 already or that are in posix but not
yet in libsmb2.

I will build a ioctl / fcntl implementation anyway since we will need ot
for thigs like detecting dfc referrals, server side copy etc.
Any case,  a Write+Read implementation for net share enum shoould be
trivially converted to use fcntl at a later stage.

**Comment by amosavian** [comment]
In Apple, `O_EXCL` is highest with value equals to`0x800`. I don't know about Linux and Windows

**Comment by amosavian** [comment]
These are all flags and their values in Darwin

<img width="618" alt="screen shot 1397-03-08 at 3 40 02 pm" src="https://user-images.githubusercontent.com/6725192/40655432-99b50184-6356-11e8-94b4-180eaa220486.png">

**Comment by sahlberg** [comment]
Linux goes all the way to #define __O_TMPFILE 020000000
i.e. 0x00400000

If you pick 0x80000000 it should be safe enough

**Comment by amosavian** [comment]
I have a better idea, why not define `O_NOOVERWRITE` flag?

**Comment by amosavian** [comment]
I've tested user-defined O_NOOVERWRITE flag and it fixed issue with opening file handle for `srvsvc`. But It seems Apple's strict implementation doesn't allow to interoperate with this pipe via READ/WRITE commands, whereas Windows and Samba does allow.

Interestingly, according to [Microsoft examples on named pipes](https://msdn.microsoft.com/en-us/library/cc246794.aspx), both READ/WRITE and IOCTL can handle this, and the only difference is number of request/responses.

Indeed this is a bug is Apple's custom server implementation of SMB2 protocol.

**Comment by amosavian** [comment]
I've finally figured out what was Apple's problem. It was my fault. I had to set offset to 0 on every read and write. Now issue fixed and I can enumerate shares on Apple without IOCTL.

**Comment by sahlberg** [comment]
Nice work!

If you implement this using Create/Write/Read/Close for now,
please add this as new file   lib/smb2-cmd-share-enum.c or similar, don't put it in libsmb2.c for now.

This means that your other patch to add O_NOOVERWRITE, that should go into libsmb2-private.h and not libsmb2.c.
(Having it private for now until and if we see a need to make it publicly visible)


Async code can be intimidating at first if you are not familiar with it.
If that is the case, you can implement this as a simple function that just uses the sync version of 
open//write//read/close   and I can refactor it later to become async.


This is exciting! Getting share enumeration working !

**Comment by amosavian** [comment]
Unfortunately I don't know C nor I do know libsmb2 internals. I did my best for a draft implementation. Please see and check it.

https://gist.github.com/amosavian/1bfc261ff33bf59684a9248ca1a82a06

Reference implementations are [MSRPC.swift](https://github.com/amosavian/AMSMB2/blob/master/AMSMB2/MSRPC.swift) and [listShare() function](https://github.com/amosavian/AMSMB2/blob/master/AMSMB2/AMSMB2.swift#L123-L172) inside my project.

Meanwhile we should find a better name for `O_NOOVERWRITE`

**Comment by stefbon** [comment]
2018-05-31 16:50 GMT+02:00 Amir Abbas Mousavian <notifications@github.com>:

> Unfortunately I don't know C nor I do know libsmb2 internals. I did my
> best for a draft implementation. Please see and check it.
>
> https://gist.github.com/amosavian/1bfc261ff33bf59684a9248ca1a82a06
>

Maybe you can look at the module of VLC recently added to browse and access
shares of CIFS servers.

See:

https://github.com/videolabs/libdsm

Stef

**Comment by amosavian** [comment]
Indeed I studied that lib and it helped me in initial implementation, after that I used wireshark for debuging.

I changed some parts, like encoding guid, to make the core more readable and consistant.

**Comment by sahlberg** [comment]
I decided to start building something more generic we can use for DCERPC in general instead
of something that just contain pre-cooked arrays of values.

Initial wip here:
https://github.com/sahlberg/libsmb2/commit/98854ef814b9760e76833b1d4eabbeccf93ef84a
It encodes either NDR32 or NDR64 depending on what the server prefers and can send validly
formed NetShareEnum calls for level 1 (name, type, comment) info.

I still need to add decoders and decode the blob the server returned. Which will require some thinking about how to track memory and how to handle memory allocations without leaking.
But we are getting there.

We might not just get a NetShareEnum function but simple dcerpc runtime we can use to do other kind of RPC calls with too.

**Comment by amosavian** [comment]
That's great. There are other pipes like `lprsvc` which can be used for printing job. Maybe we will implement print functionality in future?
 
As I see you also use write/read instead of ioctl command. 😀 However It made number of callbacks folded by two.

`nse_enum_read_cb` is not implemented yet?

**Comment by sahlberg** [comment]
Correct, I have not implemented nse_enum_read_cb yet.

I need to think about how memory managment will work before I start implementing too much of it.
But it should not be too difficult to come up with something workable.

Just give me some time.

**Comment by amosavian** [comment]
About memory management, I don't know what you exactly mean. But for internal use, you can implement a reference counting system.

**Comment by amosavian** [comment]
Hey @sahlberg,

Would you mind consider implementing `FSCTL_GET_REPARSE_POINT`, `FSCTL_SET_REPARSE_POINT` and `FSCTL_DELETE_REPARSE_POINT` for symbolic links as `readlink()` and `symlink()` functions?

**Comment by sahlberg** [comment]
Hi @amosavian 
I can sure add those FCNTL functions too.
Please open a new issue for each of the ones you want and I will add them after the next release.

I will close this issue for now since we do have SMB2_IOCTL now

**Comment by thegeekyboy** [comment]
hi @sahlberg were you able to implement the server side copy feature? I was kind of in need of it :)
