### ISSUE TITLE
[Request] Timeout functionality

### ISSUE THREAD

**Issue by jsjqian** [sahlberg/libsmb2#51]
Hi,

I am trying to add a timeout for one of the library functions in libsmb2 but have been unable to find an implementation within the library. I am also using the libnfs library and found a way to timeout a call [here](https://github.com/sahlberg/libnfs/blob/63ba842be99483e11342ba2db148df83e85b4212/lib/libnfs.c#L1953). Does some sort of timeout system exist within libsmb2 and if so, does it follow a similar pattern?

Thanks!

**Comment by sahlberg** [comment]
I have not added timeout handling to libsmb2 yet.
I will at some stage and then it will likely look very similar to how it is used in libnfs.

**Comment by timmeh87** [comment]
here is my implementation

static int wait_for_reply(struct smb2_context *smb2,
                          struct sync_cb_data *cb_data)
{
	int tlimit = 5; //seconds
	time_t rawtime;
	time(&rawtime);
	uint64_t timeout = 0;
	
    while (!cb_data->is_finished && (timeout < tlimit))
	{
		time_t rawtime2;
		time(&rawtime2);
		timeout = rawtime2 - rawtime;

		struct pollfd pfd;
		pfd.fd = smb2_get_fd(smb2);
		pfd.events = smb2_which_events(smb2);

		if (poll(&pfd, 1, 1000) < 0) 
		{
			smb2_set_error(smb2, "Poll failed");
			return -1;
		}
        if (pfd.revents == 0)
		{
                continue;
        }
		if (smb2_service(smb2, pfd.revents) < 0) 
		{
			smb2_set_error(smb2, "smb2_service failed with : %s\n", smb2_get_error(smb2));
            return -1;
		}
	}

	if (timeout == tlimit)
	{
		smb2_set_error(smb2, "smb2_service failed with timeout");
		return -1;
	}
    return 0;
}

**Comment by sahlberg** [comment]
Current master has timeout handling for both async and sync api
