### ISSUE TITLE
Memory leak in smb2_set_password

### ISSUE THREAD

**Issue by amosavian** [sahlberg/libsmb2#54]
Hi,

Xcode says I have a 16 bytes leak by malloc and traces to `smb2_set_password` function.

<img width="307" alt="screen shot 1397-03-25 at 15 34 53" src="https://user-images.githubusercontent.com/6725192/41465074-cc6cfc22-70b1-11e8-8aea-086f86c0b41f.png">

**Comment by amosavian** [comment]
I've checked the memory region contains my password

**Comment by sahlberg** [comment]
fixed in current master
