### ISSUE TITLE
smb2_cmd_ioctl_async reply corrupted

### ISSUE THREAD

**Issue by amosavian** [sahlberg/libsmb2#65]
I implemented server-side copy using ioctl command. Occasionally `smb2_ioctl_reply` returned by async handler is corrupted and `output_count` has weird values like `2939741608`. In this condition, when I try to free `output` memory using `smb2_free_data()`, I get `SIGABRT`.

This issue always happens when I try to copy two files simultaneously using same smb2_context.

Unfortunately I can't ignore reply otherwise I will have memory leaks.

Furthermore, reply's `ctl_code` always mismatch with request's one.

Error is: `malloc: *** error for object 0x1c81575f8: pointer being freed was not allocated`

**Comment by amosavian** [comment]
@sahlberg any progress on this issue did you have?

**Comment by sahlberg** [comment]
Can you get a network trace when this happens?

**Comment by amosavian** [comment]
@sahlberg As I remember, I could not. I will try to wireshark it again. I’ll inform you about result then.

**Comment by sahlberg** [comment]
I think this should be fixed now.
