### ISSUE TITLE
Failed to parse fixed part of command payload. Unexpected size of Create. Expected 89, got 88

### ISSUE THREAD

**Issue by haihongwang** [sahlberg/libsmb2#68]
Encountered this error when using libsmb2 APIs to iterate through a directory tree on an Isilon SMB server. I will attach a tcpdump trace when the problem is happening.

**Comment by haihongwang** [comment]
![image](https://user-images.githubusercontent.com/28880608/44822276-13865f80-abaf-11e8-90f2-f8c4c2095faf.png)

Can't upload tcp trace file, so just an image of the offending response is attached

**Comment by sahlberg** [comment]
You can email it to me at ronniesahlberg@gmail.com

**Comment by haihongwang** [comment]
It appears to be an Isilon SMB server bug, but it prevents libsmb2 clients from making progress iterating the directory though. Maybe the best way is to ignore such bad response.

**Comment by sahlberg** [comment]
This has been fixed a while ago
