### ISSUE TITLE
smb2_cmd_create_async failed on xcode 10.2

### ISSUE THREAD

**Issue by kasimok** [sahlberg/libsmb2#81]
Hi sahlberg
     I have been using AMSMB2 which is based on this repo for a long time, it works great, but with the update on Xcode10.2, the list share API failed. I ran the test case of `func testShareEnum() ` of AMSMB2's [test case](https://github.com/amosavian/AMSMB2/blob/master/AMSMB2Tests/AMSMB2Tests.swift). The case success on xcode10.1 but failed on xcode10.2. After some debug, I found it was caused by `smb2_cmd_create_async` API.
<img width="993" alt="Screenshot 2019-03-29 at 2 26 05 PM" src="https://user-images.githubusercontent.com/5194603/55213560-a0b99180-522e-11e9-926e-57a4870aee74.png">
Can you please take a look? Is it a xcode issue and do we have a workaround?

**Comment by amosavian** [comment]
I think this issue should be handled on AMSMB2

**Comment by kasimok** [comment]
> I think this issue should be handled on AMSMB2

Hi, amosavian. You have any clue on this issue? Xcode10.1 works perfectly and Xcode10.2 just fails.

**Comment by amosavian** [comment]
I'm on vacation. I didn't download Xcode 10.2 and didn't test any code against the new version.

**Comment by amosavian** [comment]
@kasimok please close this issue
