### ISSUE TITLE
Writes truncate files

### ISSUE THREAD

**Issue by noahmorrison1** [sahlberg/libsmb2#82]
It looks like we have the following code for file open:

        /* Create disposition */
        if (flags & O_CREAT) {
                if (flags & O_EXCL) {
                        create_disposition = SMB2_FILE_CREATE;
                } else {
                        create_disposition = SMB2_FILE_OVERWRITE_IF;
                }
        } else {
                if (flags & (O_WRONLY | O_RDWR)) {
                        create_disposition = SMB2_FILE_OVERWRITE;
                } else {
                        create_disposition = SMB2_FILE_OPEN;
                }
        }

This is a bug as it causes all writes to truncate files.

O_WRONLY | O_RDWR   should be O_TRUNC

**Comment by noahmorrison1** [comment]
we are actually now thinking


                if (flags & O_EXCL) {
                        create_disposition = SMB2_FILE_CREATE;
                } else if(flags & O_TRUNC) {
                        create_disposition = SMB2_FILE_OVERWRITE_IF;
                } else {
                        create_disposition =SMB2_FILE_OPEN_IF;
                }
        } else {
                // Rubrik modification. This used to be O_WRONLY | O_RDWR
                // which caused all writes to truncate files
                if (flags & O_TRUNC) {
                        create_disposition = SMB2_FILE_OVERWRITE;
                } else {
                        create_disposition = SMB2_FILE_OPEN;
                }

**Comment by sahlberg** [comment]
Awesome. Merged.

Thanks!
