### ISSUE TITLE
Support server:port syntax?

### ISSUE THREAD

**Issue by mwyoungpa** [sahlberg/libsmb2#85]
The port to use is hardwired in socket.cc to be CIFS_PORT (445).
In order to support a server accessed through an SSH tunnel, I'd like
to be able to specify a port for the SMB server.

Would you be willing to accept a code change to accept an optional :port suffix
after the host name?

**Comment by sahlberg** [comment]
On Sat, May 11, 2019 at 11:40 AM mwyoungpa <notifications@github.com> wrote:

> The port to use is hardwired in socket.cc to be CIFS_PORT (445).
> In order to support a server accessed through an SSH tunnel, I'd like
> to be able to specify a port for the SMB server.
>
> Would you be willing to accept a code change to accept an optional :port
> suffix
> after the host name?
>

That sounds reasonable.

**Comment by sahlberg** [comment]
That sounds reasonable.
