### ISSUE TITLE
Porting to ESP32

### ISSUE THREAD

**Issue by apuder** [sahlberg/libsmb2#89]
Hi,
I'm trying to port libsmb2 to an ESP32. Unfortunately the ESP32 does not support poll() at this time. Although configure checks for HAVE_POLL_H, libsmb2 does not compile without that header file. I think it should be possible to revert to a strictly synchronous API in that case. Any guidance on how to go about that? Simply marking the socket as blocking and doing a no-op in wait_for_reply() doesn't work.
TIA,
AP

**Comment by sahlberg** [comment]
Hi,

ESP32. Very cool.

You don't support select() either I guess? So we need a full rewrite of
some (small) parts.

I don't think it should be too hard. It would involve ifdefing out the code
to mark the socket as non-blocking, small changes to smb2_service() as well
as a rewrite of the eventloop for sync commands.
Should not be terribly hard. If it adds support for a microcontroller like
ESP32 that would be awesome.


Let me look into this. I am happy to create a special branch of libsmb2
with a patch for platforms without select/poll/non-blocking support.
I will try to do this over the weekend. If you don't hear from me by next
week, ping me and remind me. I am forgetful.

I really think it would be cool to have smb2 support for that uC.

regards
ronnie sahlberg

**Comment by apuder** [comment]
Some quick updates: the ESP32 does indeed have an implementation for poll(). The header file is in <sys/poll.h>. However, the ESP32 is missing readv() and writev() although it is easy to provide a substitute implementation. Now I'm stuck at libsmb2 sending a PDU but then does not receive a response. I haven't figured out yet what is going on. I'll do some more testing over the weekend as well and report back.

**Comment by apuder** [comment]
Update 2: portable-endian.h seemed to think that the ESP32 is a big endian system (which it is not). That wreaked havoc on byte ordering and explains the issue I was having. This is most likely an issue with the ESP32 SDK. A little tweak to portable-endian.h fixed that problem. However, now I get the error "Session setup failed with (0xc000006d) STATUS_LOGON_FAILURE". I am using the same test program than on my PC so I know that URL and credentials are correct. I suspect another small incompatibility with the ESP32 SDK. Any suggestions on what the cause might be?

**Comment by apuder** [comment]
Resolved the issue via an offline discussion with Ronnie. The core problem is an incompatibility with the ESP32 SDK's implementation of hmac_md(). I'll prepare a PR that will allow libsmb2 to be used on an ESP32.
