### ISSUE TITLE
Query server for shares.

### ISSUE THREAD

**Issue by stefbon** [sahlberg/libsmb2#9]
Hi,

can I use libsmb2 to query a server for the different shares (and other services).
I've tried to use smb2_connect_async to connect to a server and then call smb2_opendir_async with directory "/", but it hangs. (I've modified the example smb2_ls_async).

Thanks in advance,
Stef

**Comment by sahlberg** [comment]
The SMB2 protocol does not have a mechanism to enumerate the shares on a
server. :-(

That functionality is done through DCE-RPC which is a very complex family
of protocols.
At some stage it would be nice to have both DCE-RPC as well as the
interfaces that are defined ontop of it
to be able to access the registry and other useful things, including
accessing the SERVER endpoint
and enumerating the shares.

DCE-RPC is enormously complex though and a huge amount of work. It may
happen at some stage but it is not
on the short or medium term roadmap.

**Comment by sahlberg** [comment]
DCE-RPC might come at some stage, but unlikely in the near future.
