### ISSUE TITLE
Release request/process

### ISSUE THREAD

**Issue by mwyoungpa** [sahlberg/libsmb2#92]
What is your process/policy for cutting a new release of libsmb2?
Would you accept a request to cut a minor release soon?
I'm interested in getting recent changes into a release so that they can
be picked up by videolan.
Thanks for your help!

**Comment by sahlberg** [comment]
On Mon, Jun 3, 2019 at 11:23 PM mwyoungpa <notifications@github.com> wrote:

> What is your process/policy for cutting a new release of libsmb2?
> Would you accept a request to cut a minor release soon?
> I'm interested in getting recent changes into a release so that they can
> be picked up by videolan.
> Thanks for your help!
>
I don't think any linux distros ship it yet so I don't really have any
particular policy.
When people ask for a new release is as good as any other policy I guess.

I will create a new release towards the end of the week.

regards
ronnie sahlberg

**Comment by sahlberg** [comment]
I have pushed a new version of libsmb2.
