### ISSUE TITLE
Need Support to build for Android

### ISSUE THREAD

**Issue by Manasa-Manchale** [sahlberg/libsmb2#93]
Currently there is no suuport to build for android. It would be great if the current make files also supports Android build. Please consider.

**Comment by sahlberg** [comment]
It does build for android.
I don't build for android myself but KODI does and other projects do.

If something is missing, please send me a patch and possibly also something
to add to README regarding how to build on android.

**Comment by sahlberg** [comment]
This builds just fine under Android
